= Griffon 2.2.0 Release Notes
Andres Almiray
2015-03-09
:jbake-type: post
:jbake-status: published
:category: releasenotes
:idprefix:
:linkattrs:
:path-griffon-core: /guide/2.2.0/api/griffon/core

== Griffon 2.2.0 Release Notes

=== Dependencies

The following dependencies have been upgraded

 * org.codehaus.groovy:groovy-all:2.4.0
 * org.slf4j:slf4j-api:1.7.10

=== Runtime

==== Application

Applications now have the capability to store key/value pairs inside a link:/guide/latest/api/griffon/core/Context.html[Context, window="_blank"].
Contexts are hierarchical, meaning a child context may shadow keys available in a parent context. Values of shadowed keys
are not modified; you can grab the original value by asking the owning context for it.

==== MVC

MVCGroups now have a link:/guide/latest/api/griffon/core/Context.html[Context, window="_blank"] of their own.
This is useful for storing group only data that can be shared between MVC members of just controller actions.
It's also possible to automatically inject context values as action arguments as long as said arguments are annotated
with link:/guide/latest/api/griffon/inject/Contextual.html[@griffon.inject.Contextual, window="_blank"].

=== Configuration

Configuration objects are made *read-only* by default. Now you can make them writable if wrapped with
link:/guide/latest/api/griffon/core/MutableConfiguration.html[MutableConfiguration, window="_blank"].

=== Compatibility

Full binary compatibility report between Griffon 2.1.0 and 2.2.0 can be found
link:../reports/2.2.0/compatibility-report.html[here].
