= Griffon 2.11.0 Release Notes
Andres Almiray
2017-09-01
:jbake-type: post
:jbake-status: published
:category: releasenotes
:idprefix:
:linkattrs:
:path-griffon-core: /guide/2.12.0/api/griffon/core

=== Dependencies

The following dependencies have been upgraded

 * org.codehaus.groovy:groovy-all:2.4.12
 * org.jetbrains.kotlin:kotlin-stdlib:1.1.3

=== Runtime


=== Buildtime

==== Gradle Wrapper

Gradle wrapper version on all Lazybones templates has been bumped to `4.0`.

=== Compatibility

==== Resources

Resource tokens have been migrated from `@token@` to `${token}`. This affects all resources found in the following directories:

 * `src/main/resources`
 * `griffon-app/resources`
 * `griffon-app/i18n`

Take note that key values may not use `.` as a separator, use `_` instead. The following keys are now available to projects
created by the Lazybones templates or those that rely on the `gradle-griffon` plugin.

|===
| Old Format          | New Format

| application.name    | application_name
| application.version | application_version
| build.date          | build_date
| build.time          | build_time
| build.revision      | build_revision
|===

==== JavaFX Gradle Plugin

All JavaFX project templates (Lazybones) now rely on link:https://github.com/FibreFoX/javafx-gradle-plugin[FibreFoX/javafx-gradle-plugin]
as it provides more features and it's updated more constantly than the previous plugin choice.

Full binary compatibility report between Griffon 2.12.0 and 2.11.0 can be found
link:../reports/2.11.0/compatibility-report.html[here].

A list of fixed issues can be found at the
link:https://github.com/griffon/griffon/issues?q=milestone%3A2.12.0+is%3Aclosed[2.12.0 milestone] page.
