#!/bin/bash

cd /usr/share
ln -s griffon-@griffon.version@ griffon
cd /usr/bin
ln -s /usr/share/griffon/bin/griffon griffon
ln -s /usr/share/griffon/bin/griffon-debug griffon-debug
ln -s /usr/share/griffon/bin/startGriffon startGriffon
# echo "export GRIFFON_HOME=/usr/share/griffon" >> /etc/environment
# source /etc/environment
