
[[_events_publishing]]
= Publishing Events

Any instance that obtains a reference to an +{link_event_router}+ can publish events.
+{link_griffon_application}+ exposes the application wide +EventRouter+ via a read-only
property. You may use Dependency Injection to inject an +EventRouter+ to any class too.

Publishing an event can be done synchronously on the current thread, asynchronously to
the current thread, or asynchronously relative to the UI thread. For example, the following
snippet will trigger an event that will be handled in the same thread, which could be the
UI thread itself

[source,groovy]
[subs="verbatim,attributes"]
----
application.eventRouter.publish('MyEventName', ['arg0', 'arg1'])
----

Whereas the following snippet guarantees that all event handlers that are interested in
an event of type +MyEventName+ will be called outside of the UI thread

[source,groovy]
[subs="verbatim,attributes"]
----
application.eventRouter.publishOutsideUI('MyEventName', ['arg0', 'arg1'])
----

Finally, if you'd want event notification to be handed in a thread that is not the current
one (regardless if the current one is the UI thread or not) then use the following method

[source,groovy]
[subs="verbatim,attributes"]
----
application.eventRouter.publishAsync('MyEventName', ['arg0', 'arg1'])
----

Alternatively, you may specify an instance of a subclass of +{link_event}+ as the sole
argument to any of these methods. The event instance will be the single argument sent
to the event handlers when the +event+ methods are invoked in this way.

There may be times when event publishing must be stopped for a while. If that's the
case then you can instruct the application to stop delivering events by invoking the
following code

[source,groovy]
[subs="verbatim,attributes"]
----
application.eventRouter.eventPublishingEnabled = false
----

Any events sent through the application's event bus will be discarded after that call;
there's no way to get them back or replay them. When it's time to enable the event bus
again simply call

[source,groovy]
[subs="verbatim,attributes"]
----
application.eventRouter.eventPublishingEnabled = true
----
