
[[_introduction]]
= Introduction
:numbered!:

Developing desktop/RIA applications on the JVM is a hard task. You have to make
choices upfront during application design that might complicate the implementation,
compromising the user experience; not to mention the amount of configuration needed.

RCP solutions like Eclipse RCP and NetBeans RCP are great for developing desktop
applications, not so much for RIAs and applets. Griffon is a framework inspired by
http://grails.org[Grails], whose aim is to overcome the problems you may encounter
while developing all these types of applications. It brings along popular concepts like

 . Convention over Configuration
 . Don't Repeat Yourself (DRY)
 . Pervasive MVC
 . Testing supported "out of the box"

This documentation will take you through getting started with Griffon and building
desktop/RIA applications with the Griffon framework.

== Credits and Acknowledgements

This guide is heavily influenced by the http://grails.org/doc/latest[Grails Guide].
It simply would not have been possible without the great efforts made by:
http://twitter.com/graemerocher[Graeme Rocher], http://twitter.com/pledbrook[Peter Ledbrook],
http://twitter.com/wangjammer5[Marc Palmer], http://twitter.com/jeffscottbrown[Jeff Brown]
and their sponsor: SpringSource. The Griffon team would like to thank them all
(and the Grails community too!) for making such a great framework and bringing the
fun back to programming applications.

:numbered:
