
[[_overview_modules]]
= Modules

{link_module}s define components that can be injected using the JSR 330 API.
Module definitions are highly influenced by the Guice 3.x API however they do not
impose a strict dependency on Guice.


Modules perform their duties by defining bindings, of which there are 4 kinds

 * {link_instance_binding}
 * {link_target_binding}
 * {link_provider_binding}
 * {link_provider_type_binding}

Bindings have an scope, either +singleton+ or +prototype+. +InstanceBinding+ is the only
binding that has +singleton+ as implicit scope; this setting can't be changed.
All bindings accept a +classifier+ or an +classifier_type+. Classifiers are annotations that
have been annotated with +@Qualifier+. You must specify one or the other but not both;
+classifier+ has precedence over +classifier_type+.

[[_overview_instance_binding]]
== Instance Binding

This binding is used to define explicit and eager singletons, for example

[source,java,options="nowrap"]
[subs="attributes"]
----
bind(Calculator.class)
    .toInstance(new GroovyShellCalculator());
----

[[_overview_target_binding]]
== Target Binding

This binding enables you to specify the _source_ type and _target_ type. Typically the
_source_ is an interface while the _target_ is a concrete implementation. If the _target_
is ommitted then the binding assumes the _source_ to be a concrete type.

[source,java,options="nowrap"]
[subs="attributes"]
----
bind(Calculator.class)
    .to(GroovyShellCalculator.class);
----

[[_overview_provider_binding]]
== Provider Binding

This binding behaves like a factory, giving you the power to decide with extreme precision
how should the instance be created. Bindings of this type require an eager instance of
type +Provider+.

[source,java,options="nowrap"]
[subs="attributes"]
----
bind(Calculator.class)
    .toProvider(new CalculatorProvider());
----

[[_overview_provider_type_binding]]
== Provider Type Binding

Finally we have the most flexible binding as it lets you specify a +Provider+ type that
will be used to lazily instantiate the provider before obtaining the type instance.

[source,java,options="nowrap"]
[subs="attributes"]
----
bind(Calculator.class)
    .toProvider(CalculatorProvider.class);
----

