
[[_views_builder_customizers]]
= BuilderCustomizers

Recall from the <<_getting_started_console_example_view,ConsoleView>> sample application
that you can use a Groovy DSL for building View components when the main language
of the application is Groovy. This DSL is configured with default nodes that are
tightly coupled with the chosen UI toolkit.

== Extending the UI DSL

The UI DSL can be extended by registering new ``{link_builder_customizer}``s with the application
using a `{link_module}`. The `{link_builder_customizer}` instance defines methods
that can be used to configure every aspect of `groovy.factory.FactoryBuilderSupport`.
Here's an example of the `miglayout-swing` extension:

.src/main/java/griffon/builder/swing/MiglayoutSwingBuilderCustomizer.java
[source,java,linenums,options="nowrap"]
----
package griffon.builder.swing;

import griffon.annotations.inject.DependsOn;
import groovy.swing.factory.LayoutFactory;
import net.miginfocom.swing.MigLayout;
import groovy.util.Factory;
import org.codehaus.griffon.runtime.groovy.view.AbstractBuilderCustomizer;

import javax.inject.Named;
import java.util.LinkedHashMap;
import java.util.Map;

@DependsOn("swing")
@Named("miglayout-swing")
public class MiglayoutSwingBuilderCustomizer extends AbstractBuilderCustomizer {
    public MiglayoutSwingBuilderCustomizer() {
        Map<String, Factory> factories = new LinkedHashMap<>();
        factories.put("migLayout", new LayoutFactory(MigLayout.class));
        setFactories(factories);
    }
}
----

This customizer registers a single factory, `miglayout`. It also defines a dependency
on the `swing` customizer in order for its customizations to be applied after ``swing``'s.
The customizer is registered using the following {link_module}.

.src/main/java/org/codehaus/griffon/runtime/miglayout/MiglayoutSwingGroovyModule.java
[source,java,linenums,options="nowrap"]
----
package org.codehaus.griffon.runtime.miglayout;

import griffon.builder.swing.MiglayoutSwingBuilderCustomizer;
import griffon.core.injection.Module;
import griffon.annotations.inject.DependsOn;
import griffon.util.BuilderCustomizer;
import org.codehaus.griffon.runtime.core.injection.AbstractModule;
import org.kordamp.jipsy.ServiceProviderFor;

import javax.inject.Named;

@DependsOn("swing-groovy")
@Named("miglayout-swing-groovy")
@ServiceProviderFor(Module.class)
public class MiglayoutSwingGroovyModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        bind(BuilderCustomizer.class)
            .to(MiglayoutSwingBuilderCustomizer.class)
            .asSingleton();
    }
}
----

This module is loaded before `swing-groovy`, as per the `{link_depends_on}` definition,
thus ensuring that the customizations from this customizer are applied afterwards.

== Default DSL Nodes

The `griffon-groovy` dependency delivers the following nodes:

=== MetaComponent

Enables the usage of a meta-component as a View node. Meta-components are MVC groups
that contain additional configuration, for example:

[source,groovy,linenums,options="nowrap"]
----
mvcGroups {
    'custom' {
        model      = 'sample.CustomModel'
        view       = 'sample.CustomView'
        controller = 'sample.CustomController'
        config {
            component = true
            title = 'My Default Title'
        }
    }
}
----

The `metaComponent()` node instantiates the MVC group and attaches the top node from
the groups' View member into the current hierarchy. Using the previous group definition
in a View is straightforward:

[source,groovy,options="nowrap"]
----
metaComponent('custom', title: 'Another Title')
----

== Default Builder Delegates

The `griffon-groovy` dependency delivers the following delegates:

=== Root

Identifies the root node of a View. Views may identify the root node. The root node is the first
node call invoked on the builder member.

.griffon-app/views/com/acme/Sample.groovy
[source,groovy,linenums,options="nowrap"]
----
package org.example

import griffon.core.artifact.GriffonView
import griffon.annotations.inject.MVCMember
import org.kordamp.jipsy.ServiceProviderFor
import griffon.annotations.core.Nonnull

@ServiceProviderFor(GriffonView)
class SampleView {
    @MVCMember @Nonnull FactoryBuilderSupport builder

    void initUI() {
        builder.with {
            button(id: 'clickActionTarget', clickAction)
        }
    }
}
----

.griffon-app/views/com/acme/PrimaryView.groovy
[source,groovy,linenums,options="nowrap"]
----
package com.acme

import griffon.core.artifact.GriffonView
import griffon.annotations.inject.MVCMember
import org.kordamp.jipsy.ServiceProviderFor
import griffon.annotations.core.Nonnull

@ServiceProviderFor(GriffonView)
class PrimaryView {
    @MVCMember @Nonnull FactoryBuilderSupport builder

    void initUI() {
        builder.with {
            application(title: 'Sample') {
                borderLayout()
                label 'Options', constraints: NORTH
                node createMVCGroup('sample').rootNode
            }
        }
    }
}
----

You may also define an explicit `rootNode` attribute with a boolean value on the target node that should be
treated as the root.

