
[[_views_javafx]]
= JavaFX Specific

Refer to the <<_builder_nodes_javafx,list of nodes>> which become available when
the `griffon-javafx-groovy-{griffon-version}.jar` is added as a dependency.

== I18n Support

Nodes of type `Labeled` can react to changes made to the application's `Locale` provided you
supply enough information to resolve the target message. `{link_javafxutils}` exposes 3 synthetic
properties and 1 connect method to make this feature work. You may use these properties with
FXML, for example

[source, xml]
[subs="verbatim"]
----
<Label JavaFXUtils.i18nKey="key.label"
       JavaFXUtils.i18nArgs="one, two"
       JavaFXUtils.i18nDefaultValue="No value supplied"/>
----

These values are used in combination with `{link_message_source}` to resolve a message and set it
as the value of the node's `text` property. The message will be resolved again anytime the application's
`Locale` changes value. You must use the connect method on the `View` class too, by invoking the
following method during UI construction

[source, java]
----
connectMessageSource(node);
----

Where `node` is the root of the hierarchy.

== Action Support

Actions can be attached to JavaFX nodes defined in two ways:

 * By defining a node id that follows the `<action_name>ActionTarget` naming convention.
 * By invoking `JavaFXUtils.setGriffonActionId()` with the target node and action id as arguments.

Both methods work whether you create the UI using the JavaFX API directly or with FXML. The advantage
of the second option is that you can link mutliple nodes to the same action. Once action ids have been
set on the target nodes you must still establish a connection between the configured nodes and the
controller; this task is attained by invoking the following method during UI construction in the `view`

[source, java]
----
connectActions(node, controller);
----

Where `node` is the root of the hierarchy. Here's an example of 3 actions being used by two different
controls each:

[source, xml]
[subs="verbatim,attributes"]
----
<?import griffon.javafx.support.JavaFXUtils?>
...
<VBox>
    <MenuBar>
        <Menu text="File">
            <MenuItem JavaFXUtils.griffonActionId="cut"/>
            <MenuItem JavaFXUtils.griffonActionId="copy"/>
            <MenuItem JavaFXUtils.griffonActionId="paste"/>
        </Menu>
    </MenuBar>
    <ToolBar>
        <Button JavaFXUtils.griffonActionId="cut"/>
        <Button JavaFXUtils.griffonActionId="copy"/>
        <Button JavaFXUtils.griffonActionId="paste"/>
    </ToolBar>
</VBox>
----

In contrast this is how the FXML would look if node ids would be set instead

[source, xml]
[subs="verbatim,attributes"]
----
...
<VBox>
    <ToolBar>
        <Button fx:id="cutActionTarget"/>
        <Button fx:id="copyActionTarget"/>
        <Button fx:id="pasteActionTarget"/>
    </ToolBar>
</VBox>
----

In this case we can't assign the same action to a different node because the node ids would clash. It's possible to override
this naming convention by defining your own strategy. Simply implement `{link_actionmatcher}`, making sure to bind your
custom strategy with module binding, such as

.org/example/ApplicationModule.java
[source,java,linenums,options="nowrap"]
----
package org.example;

import griffon.core.injection.Module;
import org.codehaus.griffon.runtime.core.injection.AbstractModule;
import org.kordamp.jipsy.ServiceProviderFor;
import griffon.javafx.support.ActionMatcher;
import griffon.annotations.inject.DependsOn;

@DependsOn("javafx")
@ServiceProviderFor(Module.class)
public class ApplicationModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        bind(ActionMatcher.class)
            .to(MyActionMatcher.class)
            .asSingleton();
    }
}
----

NOTE: Be aware that using the standard FXML notation (`#actionName`) for event handlers is not compatible with Griffon actions!

FXML conventions dictate that the argument specified in `fx:controller` defines the type on which node injections via
`@FXML` will take place. It's also the source for any event handler defined using the format `#<actionName>` where `<actionName>`
matches a public method that takes the required event type as argument. In othwer words, the following code shows a simple
FXML controller

[source, java]
.com/acme/SampleView.java
----
package com.acme;

import javafx.scene.control.Label;
import javafx.event.ActionEvent;

public class SampleView {
    @FXML private void myLabel;

    @FXML
    public void initialize() {
        myLabel.setText("random text");
    }

    public void click(ActionEvent ignored) { ... }
}
----

[source, xml]
[subs="verbatim,attributes"]
.com/acme/sample.fxml
----
<?xml version="1.0" encoding="UTF-8"?>
<?import javafx.scene.control.Button?>
<?import javafx.scene.control.Label?>
<?import javafx.scene.control.VBox?>
<VBox xmlns:fx="http://javafx.com/fxml/1" xmlns="http://javafx.com/javafx/8"
      fx:controller="com.acme.SampleView">
    <Label fx:id="myLabel"/>
    <Button text="click" onAction="#click"/>
</VBox>
----

Notice that the name `SampleView` was chosen on purpose. This demonstrates one of the problems with the concept behind
`fx:controller`, as it defines both the place where widgets may be configured and the source of event handlers. The first
is the sole responsibility of a View component while the latter is the responsibility of a Controller. Griffon decided to
split these responsibilities into their proper MVC members; thus the previous example can be rewritten as follows:

[source, java]
.griffon-app/controllers/com/acme/SampleController.java
----
package com.acme;

import griffon.core.artifact.GriffonController;
import griffon.core.controller.ControllerAction;
import org.kordamp.jipsy.ServiceProviderFor;
import org.codehaus.griffon.runtime.core.artifact.AbstractGriffonController;
import javafx.event.ActionEvent;

@ServiceProviderFor(GriffonController.class)
public class SampleController extends AbstractGriffonController {
    @ControllerAction
    public void click(ActionEvent ignored) { ... }
}
----

[source, java]
.griffon-app/views/com/acme/SampleView.java
----
package com.acme;

import griffon.core.artifact.GriffonView;
import griffon.annotations.inject.MVCMember;
import org.kordamp.jipsy.ServiceProviderFor;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import org.codehaus.griffon.runtime.javafx.artifact.AbstractJavaFXGriffonView;
import griffon.annotations.core.Nonnull;

@ServiceProviderFor(GriffonView.class)
public class SampleView extends AbstractJavaFXGriffonView {
    @MVCMember @Nonnull
    private SampleController controller;

    @FXML private void myLabel;

    @Override
    public void initUI() {
        VBox content = loadFromFXML();
        myLabel.setText("random text");
        connectActions(content, controller);
        connectMessageSource(content);
        // add content to SceneGraph ...
    }
}
----

[source, xml]
[subs="verbatim,attributes"]
.griffon-app/resources/com/acme/sample.fxml
----
<?xml version="1.0" encoding="UTF-8"?>
<?import javafx.scene.control.Button?>
<?import javafx.scene.control.Label?>
<?import javafx.scene.control.VBox?>
<?import griffon.javafx.support.JavaFXUtils?>
<VBox xmlns:fx="http://javafx.com/fxml/1" xmlns="http://javafx.com/javafx/8"
      fx:controller="com.acme.SampleView">
    <Label fx:id="myLabel"/>
    <Button JavaFXUtils.griffonActionId="click"/>
    <!--
        As an alternative you may define the Button like this too
        <Button fx:id="clickActionTarget"/>
    -->
</VBox>
----

There may be cases where you would still like to use the standar FXML event handlers, for exmaple where an event handler
is UI specific such a focus handler or a scroll handler. In this case you would define the event handler as a public
method on the View class.

== Binding Support

=== Collections

`{link_collection_bindings}` class provides binding factories on `ObservableList`/`ObservableSet`/`ObservableMap`

 * Join source observable collection to `StringBinding`.
 * Calculate `min`, `max`, `average`, and `sum` on source observable collection.

=== Filtering

`{link_filtering_bindings}` class provides filtering capabilities on `ObservableList`/`ObservableSet`/`ObservableMap`

 * Filter `ObservableList`/`ObservableSet`/`ObservableMap` and find first match, creating a `ObjectBinding`.
 * Filter `ObservableList`/`ObservableSet`/`ObservableMap` then map and find first match to X; where X may be a wrapper type, String or a type `R`.
 * Map elements of `ObservableList`/`ObservableSet`/`ObservableMap` to X then filter and find first match; where X may be a wrapper type, String or a type `R`.

=== Matching

`{link_matching_bindings}` class provides matching capabilities on `ObservableList`/`ObservableSet`/`ObservableMap`

 * Apply `allMatch`, `anyMatch`, and `noneMatch` predicates.

=== Mapping

`{link_mapping_bindings}` class provides lots of useful binding and property factories

 * Convert `ObservableValue<X>` to is corresponding `XBinding`.
 * Convert `ObservableXValue` to `ObjectBinding<X>`.

=== Reducing

`{link_reducing_bindings}` class provides reduce capabilities on `ObservableList`/`ObservableSet`/`ObservableMap`

 * Reduce `ObservableList`/`ObservableSet`/`ObservableMap` to `ObjectBinding`.
 * Reduce `ObservableList`/`ObservableSet`/`ObservableMap` then map to X; where X may be a wrapper type, String or a type `R`.
 * Map elements of `ObservableList`/`ObservableSet`/`ObservableMap` to X then reduce; where X may be a wrapper type, String or a type `R`.

=== UI Thread Specific

It's very important to obey the basic rules of UI programming in the Java platform. Basically everything
related to UI must be performed inside the UI thread. Everything that's not UI related must be executed
outside the UI thread. Griffon provides the means to wrap `{link_observable_list}`, `{link_observable_set}`,
and `{link_observable_map}` with versions that guarantee to notify its listeners inside the UI thread.
This lets you write the following code in a `View` artifact:

[source, java]
----
import griffon.javafx.collections.GriffonFXCollections;
...

ObservableList<String> items = model.getItems();
ObservableList<String> uiItems = GriffonFXCollections.uiThreadAwareObservableList(items);
listView.setItems(uiItems);
----

Now every time the `items` list that belongs to the `Model` gets updated so will be the `listView` widget
with the guarantee that it doesn't matter which thread pushes the original changes the `listView` will
be updated inside the UI thread.

You may also create UI thread aware versions of `ChangeListener`, `InvalidationListener`, `ListChangeListener`,
`SetChangeListener`, `MapChangeListener`, all combinations of `Property<X>` and their specializations,
`XProperty`; where X stands for `Boolean`, `Integer`, `Long`, `Float`, `Double`, `String`, `Map`, `List`,
`Set`. The class `{link_uithreadaware_bindings}` provides the means to create these type of bindings.

== MetaComponent Support

You can use MVCGroups as components inside an FXML file. Let's assume there's an mvcGroup named `form` with a matching
`FormView`. This view defines the following content in `form.fxml`

[source, xml]
.griffon-app/resources/com/acme/form.fxml
----
<?xml version="1.0" encoding="UTF-8"?>

<?import javafx.scene.layout.VBox?>
<?import griffon.javafx.support.MetaComponent?>
<?import griffon.javafx.support.MetaComponent.MvcArg?>

<VBox xmlns:fx="http://javafx.com/fxml"
      fx:controller="com/acme/ContainerView">
    <MetaComponent mvcType="formItem">
        <MetaComponent.MvcArg name="key" value="name"/>
    </MetaComponent>
    <MetaComponent mvcType="formItem">
        <MetaComponent.MvcArg name="propertyKey" value="lastname"/>
    </MetaComponent>
</VBox>
----

The `formItem` MVC group defines a Label, a TextField, and handles validation for its input. `FormView` must identify
the root node that can be added to its parent view; the convention is to use the group's id plus `"-rootNode"`, for example

[source, java]
.griffon-app/com/acme/FormItemView.java
----
package org.example;

import griffon.core.artifact.GriffonView;
import griffon.annotations.inject.MVCMember;
import org.kordamp.jipsy.ServiceProviderFor;
import javafx.fxml.FXML;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import org.codehaus.griffon.runtime.javafx.artifact.AbstractJavaFXGriffonView;

import java.util.Collections;
import griffon.annotations.core.Nonnull;

@ServiceProviderFor(GriffonView.class)
public class FormItemView extends AbstractJavaFXGriffonView {
    @MVCMember private FormItemController controller;
    @MVCMember private FormItemModel model;
    @MVCMember private String propertyKey;

    @FXML private Label propertyLabel;
    @FXML private TextField propertyValue;

    @Override
    public void initUI() {
        Node content = loadFromFXML();
        propertyLabel.setText(propertyKey);
        model.valueProperty().bindBidirectional(propertyValue.textProperty());
        connectActions(content, controller);
        connectMessageSource(content);
        getMvcGroup().getContext().put(getMvcGroup().getMvcId() + "-rootNode", content); //<1>
    }
}
----
<1> Naming convention

The current naming convention to identify the root node of a View is to use the MVCGroup's id with the `-rootNode` prefix
as a key in the MVCGroup's context.

