
[[_contributing_build]]
= Build

If you're interested in contributing fixes and features to the core framework, you
will have to learn how to get hold of the project's source, build it, and test it
with your own applications. Before you start, make sure you have:

* A JDK (1.7 or above)
* A git client

Once you have all the prerequisite packages installed, the next step is to download
the Griffon source code, which is hosted at http://github.com[GitHub] in several
repositories owned by the http://github.com/griffon[`griffon` GitHub user]. This
is a simple case of cloning the repository you're interested in. For example, to
get the core framework run:

[source]
[subs="attributes"]
----
$ git clone {griffon-source-url}
----

This will create a `griffon` directory in your current working directory containing
all the project source files. The next step is to get a Griffon installation from the source.

== Running the test suite

All you have to do to run the full suite of tests is:

[source]
----
$ ./gradlew test
----

These will take a while, so consider running individual tests using the command line.
For example, to run the test case @MappingDslTests@ simply execute the following command:

[source]
----
$ ./gradlew -Dtest.single=EnvironmentTests :griffon-core:test
----

Note that you need to specify the sub-project that the test case resides in, because
the top-level "test" target won't work....

== Developing in IntelliJ IDEA

You need to run the following gradle task:

[source]
----
$ ./gradlew idea
----

Then open the project file which is generated in IDEA. Simple!
