
[[_internationalization_message_source_transformation]]
= The @MessageSourceAware AST Transformation

Any component may gain the ability to resolve messages through a `MessageSource`
instance. You only need annotate the class with `{link_message_source_aware}`
and it will automatically gain all methods exposed by `{link_message_source}`.

This feature is just a shortcut to avoid reaching for the application instance
from objects that do not hold a reference to it.

Here's an example of a custom bean that's able to resolve messages

[source,groovy,linenums,options="nowrap"]
----
@griffon.transform.MessageSourceAware
class Bean {
    String name
}
----

This class can be used in the following way

[source,groovy,linenums,options="nowrap"]
----
class SampleService {
    @Inject Bean bean

    String lookupValues(String arg) {
        bean.name = arg
        bean.getMessage('some.message.key', [bean.name])
    }
}
----

The application's `MessageSource` will be injected to annotated beans if no name is
specified as an argument to `MessageSourceAware`. You may define multiple `MessageSource`
bindings as long as you qualify them with a distinct name, such as

[source,java,linenums,options="nowrap"]
----
@ServiceProviderFor(Module.class)
@Named("application")
public class ApplicationModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        bind(MessageSource.class)
            .withClassifier(AnnotationUtils.named("foo"))
            .toProvider(new MessageSourceProvider("foofile"))
            .asSingleton();

        bind(MessageSource.class)
            .withClassifier(AnnotationUtils.named("bar"))
            .toProvider(new MessageSourceProvider("barfile"))
            .asSingleton();
    }
}
----

Then make use of any of these bindings like so

[source,groovy,linenums,options="nowrap"]
----
@griffon.transform.MessageSourceAware('foo')
class Bean {
    String name
}
----
