
[[_introduction]]
= Introduction
:numbered!:

Developing desktop/RIA applications on the JVM is a hard task. You have to make
choices up front during application design that might complicate the implementation,
compromising the user experience, not to mention the amount of configuration needed.

RCP solutions like Eclipse RCP and NetBeans RCP are great for developing desktop
applications, but not so much for RIAs and applets. Griffon is a framework inspired by
http://grails.org[Grails], whose aim is to overcome the problems you may encounter
while developing all these types of applications. It brings along popular concepts like

 . Convention over Configuration
 . Don't Repeat Yourself (DRY)
 . Pervasive MVC
 . Testing supported "out of the box"

This documentation will take you through getting started with Griffon and building
desktop/RIA applications with the Griffon framework.

== Credits and Acknowledgements

This guide is heavily influenced by the http://grails.org/doc/latest[Grails Guide].
It simply would not have been possible without the great efforts made by:
http://twitter.com/graemerocher[Graeme Rocher], http://twitter.com/pledbrook[Peter Ledbrook],
http://twitter.com/wangjammer5[Marc Palmer], http://twitter.com/jeffscottbrown[Jeff Brown]
and their sponsor: SpringSource. The Griffon team would like to thank them all
(and the Grails community too!) for making such a great framework and bringing the
fun back to programming applications.

== Background

Griffon's lineage can be traced back to Grails; the first release of the framework was posted on
September 10th 2008. At the time the team concentrated their efforts in making Griffon a lightweight
addition to what SwingBuilder offered. JavaFX was not in the radar at it was still very young and
not ready for prime time as opposed to Swing. Groovy's dynamic features made it very easy for people
to write applications with a concise syntax and a few lines of code.

JavaFX became a viable option as time passed by. Also, Griffon 2.x was revamped to support Java from
the core, not just as an after thought, same for for JavaFX and Dependency Injection. This design goal
enabled the framework to be more flexible in terms of language and UI toolkit choices. It can also
target a broader audience as there's a sizable number of developers that prefer writing Java code
rather than Groovy (or Kotlin).

Many of the examples posted since 2.x came out showcase the usage of Java to entice and convince Java
developers to give it a try. Seasoned Groovy developers know they can adapt the code using idiomatic
Groovy based on their preferences. This Guide continues to show Groovy code for brevity, opting for Java
when it makes sense for a particular feature. The documentation of most Griffon plugins also show both
Groovy and Java examples that can be Copy & Pasted as a starting point.

:numbered:
