
[[_models_observable_transformation]]
= The @Observable AST Transformation

The `{link_observable_ast}` transformation will inject the behavior of `{link_observable}`
into the annotated class. It basically injects an instance of `com.googlecode.openbeans.PropertyChangeSupport`
and all methods required to make the model an observable class. It will also make sure that
a `com.googlecode.openbeans.PropertyChangeEvent` is fired for each observable property whenever said
property changes value.

The following is a list of all methods added by `{link_observable_ast}`

 * void addPropertyChangeListener(PropertyChangeListener listener)
 * void addPropertyChangeListener(String propertyName, PropertyChangeListener listener)
 * void removePropertyChangeListener(PropertyChangeListener listener)
 * void removePropertyChangeListener(String propertyName, PropertyChangeListener listener)
 * PropertyChangeListener[] getPropertyChangeListeners()
 * PropertyChangeListener[] getPropertyChangeListeners(String propertyName)
 * void firePropertyChange(String propertyName, Object oldValue, Object newValue)
