
[[_models_vetoable_transformation]]
= The @Vetoable AST Transformation

The `{link_vetoable_ast}` transformation will inject the behavior of `{link_vetoable}`
into the annotated class. It basically injects an instance of `com.googlecode.openbeans.VetoableChangeSupport`
and all methods required to make the model a vetoable class. It will also make sure that
a `com.googlecode.openbeans.PropertyChangeEvent` is fired for each vetoable property whenever said
property changes value.

The following is a list of all methods added by `{link_vetoable_ast}`

 * void addVetoableChangeListener(VetoableChangeListener listener)
 * void addVetoableChangeListener(String propertyName, VetoableChangeListener listener)
 * void removeVetoableChangeListener(VetoableChangeListener listener)
 * void removeVetoableChangeListener(String propertyName, VetoableChangeListener listener)
 * VetoableChangeListener[] getVetoableChangeListeners()
 * VetoableChangeListener[] getVetoableChangeListeners(String propertyName)
 * void fireVetoableChange(String propertyName, Object oldValue, Object newValue)
