
[[_mvc_mvcgroups]]
= MVC Groups

Now that we know which are the different ways to instantiate MVC groups we can go
back to customizing them.

The simplest way is to pass in new values as part of the arguments map that
`{link_mvc_group_init}` receives, for example

[source,groovy,options="nowrap"]
----
MVCGroup group = application.mvcGroupManager.createMVCGroup('foo', [key: 'foo'])
----

However is you wish to use the special `config` key that every MVC group configuration
 may have then you must instantiate the group in the following way

[source,groovy,options="nowrap"]
----
MVCGroupConfiguration configuration = application.mvcGroupManager
                                          .cloneMVCConfiguration('foo', [key: 'someValue'])
MVCGroup group = configuration.create()
----

Note that you can still send custom arguments to the `create()` method.

[[_mvc_configuring_mvc_groups]]
== Configuring MVC Groups

The following options are available to all MVC groups as long as you use the `config` key.

=== Disabling Lifecycle Events

Every MVC group triggers a few events during the span of its lifetime. These events
will be sent to the event bus even if no component is interested in handling them.
There may be times when you don't want these events to be placed in the event bus
in order to speed up group creation/destruction. Use the following configuration to
gain this effect:

[source,groovy,linenums,options="nowrap"]
----
mvcGroups {
    // MVC Group for "sample"
    'sample' {
        model      = 'sample.SampleModel'
        view       = 'sample.SampleView'
        controller = 'sample.SampleController'
        config {
            events {
                lifecycle = false
            }
        }
    }
}
----

The following events will be disabled with this setting:

 - `<<_events_application_events,InitializeMVCGroup>>`
 - `<<_events_application_events,CreateMVCGroup>>`
 - `<<_events_application_events,DestroyMVCGroup>>`

=== Disabling Instantiation Events

The Griffon runtime will trigger an event for every artifact it manages. As with
the previous events this one will be sent to the event bus even if no component handles
it. Skipping publication of this event may result in a slight increase of speed during
group instantiation. Use the following configuration to gain this effect:

[source,groovy,linenums,options="nowrap"]
----
mvcGroups {
    // MVC Group for "sample"
    'sample' {
        model      = 'sample.SampleModel'
        view       = 'sample.SampleView'
        controller = 'sample.SampleController'
        config {
            events {
                instantiation = false
            }
        }
    }
}
----

The following events will be disabled with this setting:

 - `<<_events_application_events,NewInstance>>`

=== Disabling Destruction Events

This is the counterpart of the `NewInstance` event. Skipping publication of this event
may result in a slight increase of speed when a group or any artifact instance is destroyed.
Use the following configuration to gain this effect:

[source,groovy,linenums,options="nowrap"]
----
mvcGroups {
    // MVC Group for "sample"
    'sample' {
        model      = 'sample.SampleModel'
        view       = 'sample.SampleView'
        controller = 'sample.SampleController'
        config {
            events {
                destruction = false
            }
        }
    }
}
----

The following events will be disabled with this setting:

 - `<<_events_application_events,DestroyInstance>>`

=== Disabling Controllers as Application Event Listeners

Controllers are registered as application event handlers by default when a group is
instantiated. This makes it very convenient to have them react to events placed in
the application's event bus. However you may want to avoid this automatic registration
altogether, as it can lead to performance improvements. You can disable this feature
with the following configuration:

[source,groovy,linenums,options="nowrap"]
----
mvcGroups {
    // MVC Group for "sample"
    'sample' {
        model      = 'sample.SampleModel'
        view       = 'sample.SampleView'
        controller = 'sample.SampleController'
        config {
            events {
                listener = false
            }
        }
    }
}
----

You can still manually register a controller as an application event handler at any time,
with the caveat that it's now your responsibility to unregister it when the time is
appropriate, most typically during the group's destroy sequence when `{link_mvc_group_destroy}`
is invoked.

[[_mvc_mvc_group_relationships]]
== MVC Group Relationships

Instances of {link_mvc_group} can be created at any time by any other instance. If an {link_mvc_group} instance is
created explicitly by another {link_mvc_group} instance _or_ by an MVC member (such as a <<_controllers,Controller>>)
then a special link is established: the newly created {link_mvc_group} will have access to its parent {link_mvc_group}.

Here's an example. Assuming the following {link_mvc_group} configuration is in place

[source,groovy,linenums,options="nowrap"]
----
mvcGroups {
    'app' {
        model      = 'org.example.AppModel'
        view       = 'org.example.AppView'
        controller = 'org.example.AppController'
    },
    'tab' {
        model      = 'org.example.TabModel'
        view       = 'org.example.TabView'
        controller = 'org.example.TabController'
    }
}
----

An instance of the `app` {link_mvc_group} can be used to instantiate `tab` in this way

[source,groovy,options="nowrap"]
----
MVCGroup appGroup = createMVCGroup('app')
MVCGroup tabGroup = appGroup.createMVCGroup('tab')
assert appGroup == tabGroup.parentGroup
----

Parent-child relationships are established right after MVC members have been instantiated and can be accessed immediately
inside life-cycle methods such as `{link_mvc_group_init}`; this comes in handy when a child group adds new UI content to
the parent's, for example

[source,groovy,options="nowrap"]
----
class TabView {
    private JComponent tab

    void initUI() {
        tab = ... // initialize
    }

    void mvcGroupInit(Map<String, Object> args) {
        group.parentGroup.view.tabContainer.addTab(group.mvcId, tab)
    }
}
----

As a shortcut you may specify additional MVC members as properties using a `parent` prefix; when this happens the matching
parent MVC members will be injected into the child MVC member. The previous example can be rewritten as

[source,groovy,options="nowrap"]
----
class TabView {
    private JComponent tab
    AppView parentView

    void initUI() {
        tab = ... // initialize
    }

    void mvcGroupInit(Map<String, Object> args) {
        parentView.tabContainer.addTab(group.mvcId, tab)
    }
}
----

NOTE: like with the default `model`, `view` and `controller` MVC properties, the _parent_ prefix can only be combined to
form `parentModel`, `parentView` and `parentController`.

[[_mvc_mvc_group_context]]
== MVC Group Context

An `{link_mvc_group}` has its own `{link_context}`. The parent of this context is set to the context of the owner of this
`{link_mvc_group}`; thus the parent of all startup ``{link_mvc_group}``s is the application's `{link_context}`. In the
previous examples, the context of the `app` group is set as the parent of the context of the `tab` group.

The `{link_context}` of an `{link_mvc_group}` has the same lifetime of its owning group, that is, once the owning
`{link_mvc_group}` is destroyed so is the `{link_context}`.

MVC members can have some of their properties injected from the group's `{link_context}`. Either annotate a field or a
property setter with `{link_contextual}`. If the `{link_contextual}` field or argument does not have `@Named` qualifier
then the fully qualified class name of the field's or argument's type will be used as a key.

It's worth noting that failure to resolve a `{link_contextual}` injection does not result in an immediate exception; if
the key could not be found in the `{link_context}` then a `null` value will be set as value. You may annotate the field
or argument with `@Nonnull`, in which case contextual injection will fail if the named key was not found in the context
or if its value is null.

