
[[_overview_locale]]
= Locale

The `{link_griffon_application}` exposes an observable property of type `java.util.Locale`.
This property reflects the locale the application currently has. Any component can register a
listener on this property in order to be notified when the application changes locale.

You may either change the application's locale by setting a value of type `Locale` or a literal
that can be parsed as a locale. The format is

[source]
----
language[_country[_variant]]
----

where

 * *language* is an ISO 639 alpha-2 or alpha-3 language code. Example: "en" (English), "ja" (Japanese), "kok" (Konkani).
 * *country* is an ISO 3166 alpha-2 country code or UN M.49 numeric-3 area code. Example: "US" (United States), "FR" (France), "029" (Caribbean).
 * *variant* is any arbitrary value used to indicate a variation of a Locale. Example: "polyton" (Polytonic Greek), "POSIX".

Both `country` and `variant` are optional however you must specify a value for `country` before defining
a value for `variant`.

