
[[_resources_resource_resolver]]
= ResourceResolver

Applications have the ability to resolve internationalizable messages by leveraging
the behavior exposed by `{link_resource_resolver}`. This interface exposes the following methods:

 - Object resolveResource(String key)
 - Object resolveResource(String key, Locale locale)
 - Object resolveResource(String key, Object[] args)
 - Object resolveResource(String key, Object[] args, Locale locale)
 - Object resolveResource(String key, List args)
 - Object resolveResource(String key, List args, Locale locale)
 - Object resolveResource(String key, Map args)
 - Object resolveResource(String key, Map args, Locale locale)
 - Object resolveResorceValue(String key, Locale locale)

The first set throws `NoSuchResourceException` if a message could not be resolved given
the key sent as argument. The following methods take and additional `defaultValue`
parameter that may be used if no configured resource is found. If this optional parameter
were to be null then the `key` is used as the literal value of the resource; in other words,
these methods never throw `NoSuchResourceException` nor return `null` unless the passed
in `key` is null.

 - Object resolveResource(String key, Object defaultValue)
 - Object resolveResource(String key, Locale locale, Object defaultValue)
 - Object resolveResource(String key, Object[] args, Object defaultValue)
 - Object resolveResource(String key, Object[] args, Locale locale, Object defaultValue)
 - Object resolveResource(String key, List args, Object defaultValue)
 - Object resolveResource(String key, List args, Locale locale, Object defaultValue)
 - Object resolveResource(String key, Map args, Object defaultValue)
 - Object resolveResource(String key, Map args, Locale locale, Object defaultValue)

The simplest way to resolve a message thus results like this

[source,groovy,options="nowrap"]
----
getApplication().getResourceResolver().resolveResource('menu.icon')
----

The set of methods that take a `List` as arguments are meant to be used from Groovy
code whereas those that take an `Object[]` are meant for Java code; this leads to
better idiomatic code as the following examples reveal

[source,groovy,options="nowrap"]
----
getApplication().getResourceResolver()
                .resolveResource('groovy.icon.resource', ['small']))
----

[source,java,options="nowrap"]
----
getApplication().getResourceResolver()
                .resolveResource("java.icon.resource", new Object[]{"large"});
----

Of course you may also use `List` versions in Java, like this

[source,java,options="nowrap"]
----
getApplication().getResourceResolver()
                .resolveResource("hybrid.icon.resource", Arrays.asList("medium"));
----

== Message Formats

There are three types of resource formats supported by default. Additional formats may
be supported if the right plugins are installed. Resources may be configured using
either properties files or Groovy scripts, please refer to the
<<_resources_resource_resolver_configuration,configuration>> section.

=== Standard Format

The first set of resource formats are those supported by the JDK's
`http://docs.oracle.com/javase/6/docs/api/java/text/MessageFormat.html[MessageFormat]`
facilities. These formats work with all versions of the `resolveResource()` method that
take a `List` or an `Object[]` as arguments. Examples follow. First the resource
definitions stored in a properties file

[source,java,linenums,options="nowrap"]
----
menu.icon = /img/icons/menu-{0}.png
----

Assuming there are three icon files stored at `griffon-app/resources/img/icons` whose
filenames are `menu-small.png`, `menu-medium.png` and `menu-large.png`, a component may
resolve any of them with

[source,groovy,options="nowrap"]
----
Object icon = getApplication().getResourceResolver()
                              .resolveResource('menu.icon', ['large'])
----

=== Map Format

The following format is non-standard (i.e, not supported by `MessageFormat`) and can
only be resolved by Griffon. This format uses symbols instead of numbers as placeholders
for arguments. Thus the previous messages can be rewritten as follows

[source,java,linenums,options="nowrap"]
----
menu.icon = /img/icons/menu-{:size}.png
----

Which may be resolved in this manner

[source,groovy,options="nowrap"]
----
Object icon = getApplication().getResourceResolver()
                              .resolveResource('menu.icon', [size: 'large'])
----

=== Groovy format

Groovy scripts have one advantage over properties files as you can embed custom logic
that may conditionally resolve a resource based on environmental values or generate a
message on the fly. In order to accomplish this feat resources must be defined as
closures. The following message uses the value of the current running environment
to determine the text of a warning to be displayed on a label

[source,groovy,linenums,options="nowrap"]
----
import java.awt.Rectangle

direct.instance = new Rectangle(10i, 20i, 30i, 40i)
computed.instance = { x, y, w, h ->
    new Rectangle(x, y, w, h)
}
----

== Type Conversion

Note that the return value of `resolveResource` is marked as `Object` but you'll get
a `String` from the first two formats. You'll have to rely on <<_resources_property_editors,property editors>>
in order to transform the value into the correct type. <<_resources_injected_resources,Injected resources>>
are automatically transformed to the expected type.

Here's how it can be done

[source,groovy,options="nowrap"]
----
import javax.swing.Icon
import java.beans.PropertyEditor
import java.beans.PropertyEditorManager
...
Object iconValue = getApplication().getResourceResolver()
                                   .resolveResource('menu.icon', ['large'])
PropertyEditor propertyEditor = PropertyEditorManager.findEditor(Icon)
propertyEditor.setAsText(String.valueOf(iconValue))
Icon icon = propertyEditor.getValue()
----

== Reference Keys

There may be times where you would want to have a 2 keys reference the same value,
as if one key were an alias for the other. `ResourceResolver` supports the notion of
referenced keys for this matter. In order to achieve this, the value of the alias
key must define the aliased key with a special format, for example

[source,java,linenums,options="nowrap"]
----
action.icon = /img/icons/action-{0}.png
hello.icon = @[action.icon]
----

Resolving those keys results in

[source,groovy,options="nowrap"]
----
assert getApplication()
           .getResourceResolver()
           .resolveResource('action.icon', ['copy']) == '/img/icons/action-copy.png'

assert getApplication()
           .getResourceResolver()
           .resolveResource('hello.icon', ['paste']) == '/img/icons/action-paste.png'
----
