
[[_buildtools_maven]]
= Maven

Application projects can also be built using {link_maven}.
The bulk of the conventions are performed by the {link_application_master_pom}.

== Plugins

The `application-master-pom` configures the following plugins:

.application-master-pom - plugins
[cols="3*", options="header"]
|===
| Group                    | ArtifactId                        | Version
| org.codehaus.mojo        | appassembler-maven-plugin         | 2.1.0
| org.codehaus.mojo        | build-helper-maven-plugin         | 3.2.0
| org.codehaus.mojo        | exec-maven-plugin                 | 3.0.0
| pl.project13.maven       | git-commit-id-plugin              | 2.2.3
| org.codehaus.gmavenplus  | gmavenplus-plugin                 | 1.13.0
| org.apache.maven.plugins | maven-assembly-plugin             | 3.3.0
| org.apache.maven.plugins | maven-clean-plugin                | 3.1.0
| org.apache.maven.plugins | maven-changes-plugin              | 2.12.1
| org.apache.maven.plugins | maven-compiler-plugin             | 3.8.1
| org.apache.maven.plugins | maven-dependency-plugin           | 3.2.0
| org.apache.maven.plugins | maven-enforcer-plugin             | 3.0.0-M3
| org.apache.maven.plugins | maven-jar-plugin                  | 3.2.0
| org.bsc.maven            | maven-processor-plugin            | 4.5-jdk8
| org.apache.maven.plugins | maven-release-plugin              | 3.0.0-M4
| org.apache.maven.plugins | maven-resources-plugin            | 2.5.3
| org.apache.maven.plugins | maven-surefire-plugin             | 3.2.0
| org.apache.maven.plugins | maven-surefire-report-plugin      | 3.0.0-M5
| org.codehaus.mojo        | versions-maven-plugin             | 2.8.1
|===

Of which the following are applied by default:

[source,xml,linenums,options="nowrap"]
[subs="verbatim,attributes"]
----
include::{master-pom}[tags=plugins,indent=0]
----

== Dependencies

All Griffon core dependencies have been added using a `<dependencyManagement>` block as follows:

[source,xml,linenums,options="nowrap"]
[subs="verbatim,attributes"]
----
include::{master-pom}[tags=dependencyManagement,indent=0]
----

It's very important that you take special note of the dependencies ending with `-compile`. As an
application developer, these dependencies belong to the _provided_ scope, since these
dependencies contain functionality that should not be exposed at runtime, such as
compile-time metadata generation via {link_jipsy}, {link_gipsy} and other AST transformations.

You must exclude these dependencies from the `maven-surefire-plugin`. The following is the
default configuration provided by the master pom:

[source,xml,linenums,options="nowrap"]
[subs="verbatim,attributes"]
----
include::{master-pom}[tags=plugin_surefire,indent=0]
----

== Profiles

The master pom enables a few profiles to take care of special tasks.

=== Run

This profile compiles and runs the application. Enable it with `maven -Prun`.

[source,xml,linenums,options="nowrap"]
[subs="verbatim,attributes"]
----
include::{master-pom}[tags=profile_run,indent=0]
----

=== Binary

This profile packages the application using the `maven-appassembler-plugin`.
Enable it with `maven -Pbinary`.

[source,xml,linenums,options="nowrap"]
[subs="verbatim,attributes"]
----
include::{master-pom}[tags=profile_binary,indent=0]
----

=== Distribution

This profile packages the application using the `maven-assembly-plugin`.
Enable it with `maven -Pdistribution`. You must execute the `binary`
profile before running the `distribution` profile.

[source,xml,linenums,options="nowrap"]
[subs="verbatim,attributes"]
----
include::{master-pom}[tags=profile_distribution,indent=0]
----

