= ResourceResolver Configuration

Resources may be configured in either properties files or Groovy scripts.
Groovy scripts have precedence over properties files should there be two files that
match the same +basename+. The default configured +basename+ is "+resources+", thus
the application will search for the following resources in the classpath.

 - resources.properties
 - resources.groovy

Of course Groovy scripts are only enabled if you add a dependency to the +griffon-groovy+
module to your project. The default +basename+ may be changed to some other value,
or additional basenames may be specified too; it's just a matter of configuring a
link:api/griffon/core/injection/Module.html[Module] override

[source,java]
[subs="verbatim,attributes"]
----
@ServiceProviderFor(Module.class)
@Named("application")
@DependsOn("core")
public class ApplicationModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        bind(ResourceResolver.class)
            .withClassifier(named("applicationResourceResolver"))
            .toProvider(new ResourceResolverProvider("custom_basename"))
            .asSingleton();
    }
}
----

Both properties files and Groovy scripts are subject locale aware loading mechanism
described next. For a Locate set to +de_CH_Basel+ the following resources will be
searched for and loaded

 - resources.properties
 - resources.groovy
 - resources_de.properties
 - resources_de.groovy
 - resources_de_CH.properties
 - resources_de_CH.groovy
 - resources_de_CH_Basel.properties
 - resources_de_CH_Basel.groovy

Properties files and Groovy scripts used for internationalization purposes are usually
placed under +griffon-app/resources+ The default +resources.properties+ file is placed in
this directory upon creating an application using the standard project templates.