
[[_internationalization_message_source_configuration]]
= MessageSource Configuration

Messages may be configured in either properties files or Groovy scripts.
Groovy scripts have precedence over properties files should there be two files that
match the same +basename+. The default configured +basename+ is "+messages+", thus
the application will search for the following resources in the classpath.

 - messages.properties
 - messages.groovy

Of course Groovy scripts are only enabled if you add a dependency to the +griffon-groovy+
module to your project. The default +basename+ may be changed to some other value,
or additional basenames may be specified too; it's just a matter of configuring a
{link_module} override

[source,java,linenums,options="nowrap"]
----
@ServiceProviderFor(Module.class)
@Named("application")
@DependsOn("core")
public class ApplicationModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        bind(MessageSource.class)
            .withClassifier(named("applicationMessageSource"))
            .toProvider(new MessageSourceProvider("custom_basename"))
            .asSingleton();
    }
}
----

Both properties files and Groovy scripts are subject locale aware loading mechanism
described next. For a Locate set to +de_CH_Basel+ the following resources will be
searched for and loaded

 - messages.properties
 - messages.groovy
 - messages_de.properties
 - messages_de.groovy
 - messages_de_CH.properties
 - messages_de_CH.groovy
 - messages_de_CH_Basel.properties
 - messages_de_CH_Basel.groovy

Properties files and Groovy scripts used for internationalization purposes are usually
placed under +griffon-app/i18n+ The default +messages.properties+ file is placed in
this directory upon creating an application using the standard project templates.
