
[[_resources_resource_resolver_transformation]]
= The @ResourceResolverAware AST Transformation

Any component may gain the ability to resolve resources through a +ResourceResolver+
instance. You only need annotate the class with +{link_resource_resolver_aware}+
and it will automatically gain all methods exposed by +{link_resource_resolver}+.

This feature is just a shortcut to avoid reaching for the application instance
from objects that do not hold a reference to it.

Here's an example of a custom bean that's able to resolve resources

[source,groovy,linenums,options="nowrap"]
----
@griffon.transform.ResourceResolverAware
class Bean {
    String name
}
----

This class can be used in the following way

[source,groovy,linenums,options="nowrap"]
----
class SampleService {
    @Inject Bean bean

    String lookupValues(String arg) {
        bean.name = arg
        bean.resolveResource('some.resource.key', [bean.name])
    }
}
----

The application's +ResourceResolver+ will be injected to annotated beans if no name is
specified as an argument to +ResourceResolverAware+. You may define multiple +ResourceResolver+
bindings as long as you qualify them with a distinct name, such as

[source,java,linenums,options="nowrap"]
----
@ServiceProviderFor(Module.class)
@Named("application")
public class ApplicationModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        bind(ResourceResolver.class)
            .withClassifier(AnnotationUtils.named("foo"))
            .toProvider(new ResourceResolverProvider("foofile"))
            .asSingleton();

        bind(ResourceResolver.class)
            .withClassifier(AnnotationUtils.named("bar"))
            .toProvider(new ResourceResolverProvider("barfile"))
            .asSingleton();
    }
}
----

Then make use of any of these bindings like so

[source,groovy,linenums,options="nowrap"]
----
@griffon.transform.ResourceResolverAware('foo')
class Bean {
    String name
}
----
