= Sample Applications
:sample-swing-java: {rootdir}/samples/sample-swing-java
:sample-swing-groovy: {rootdir}/samples/sample-swing-groovy
:sample-javafx-java: {rootdir}/samples/sample-javafx-java
:sample-javafx-groovy: {rootdir}/samples/sample-javafx-groovy

== Swing

=== Model

.sample-swing-java/griffon-app/models/sample/SampleModel.java
[source,java]
[subs="verbatim,attributes"]
----
include::{sample-swing-java}/griffon-app/models/sample/SampleModel.java[]
----
<1> Define a private field for the property
<2> Property accessor
<3> Property mutator must fire a +PropertyChangeEvent+

.sample-swing-groovy/griffon-app/models/sample/SampleModel.groovy
[source,groovy]
[subs="verbatim,attributes"]
----
include::{sample-swing-groovy}/griffon-app/models/sample/SampleModel.groovy[]
----
<1> Observable property

=== Controller

.sample-swing-java/griffon-app/controllers/sample/SampleController.java
[source,java]
[subs="verbatim,attributes"]
----
include::{sample-swing-java}/griffon-app/controllers/sample/SampleController.java[]
----
<1> MVC member injected by +link:api/griffon/core/mvc/MVCGroupManager.html[MVCGroupManager]+
<2> Injected by JSR 330
<3> Automatically run off the UI thread
<4> Get back inside the UI thread

.sample-swing-groovy/griffon-app/controllers/sample/SampleController.groovy
[source,groovy]
[subs="verbatim,attributes"]
----
include::{sample-swing-groovy}/griffon-app/controllers/sample/SampleController.groovy[]
----
<1> MVC member injected by +link:api/griffon/core/mvc/MVCGroupManager.html[MVCGroupManager]+
<2> Injected by JSR 330
<3> Automatically run off the UI thread
<4> Get back inside the UI thread

=== Service

.sample-swing-java/griffon-app/services/sample/SampleService.java
[source,java]
[subs="verbatim,attributes"]
----
include::{sample-swing-java}/griffon-app/services/sample/SampleService.java[]
----

.sample-swing-groovy/griffon-app/services/sample/SampleService.groovy
[source,groovy]
[subs="verbatim,attributes"]
----
include::{sample-swing-groovy}/griffon-app/services/sample/SampleService.groovy[]
----

=== View

.sample-swing-java/griffon-app/views/sample/SampleView.java
[source,java]
[subs="verbatim,attributes"]
----
include::{sample-swing-java}/griffon-app/views/sample/SampleView.java[]
----
<1> MVC member injected by +link:api/griffon/core/mvc/MVCGroupManager.html[MVCGroupManager]+
<2> Attach window to +link:api/griffon/core/view/WindowManager.html[WindowManager]+
<3> Apply component-to-model binding
<4> Hook in controller action by name

.sample-swing-groovy/griffon-app/views/sample/SampleView.groovy
[source,groovy]
[subs="verbatim,attributes"]
----
include::{sample-swing-groovy}/griffon-app/views/sample/SampleView.groovy[]
----
<1> MVC member injected by +link:api/griffon/core/mvc/MVCGroupManager.html[MVCGroupManager]+
<2> Create window and attach it to +link:api/griffon/core/view/WindowManager.html[WindowManager]+
<3> Apply component-to-model binding
<4> Hook in controller action by name

=== Resources

.sample-swing-java/griffon-app/i18n/messages.properties
[source]
----
include::{sample-swing-java}/griffon-app/i18n/messages.properties[]
----

== JavaFX

=== Model

.sample-javafx-java/griffon-app/models/sample/SampleModel.java
[source,java]
[subs="verbatim,attributes"]
----
include::{sample-javafx-java}/griffon-app/models/sample/SampleModel.java[]
----
<1> Define a private field for the property
<2> Property accessor
<3> Pass-thru values to +Property+

.sample-javafx-groovy/griffon-app/models/sample/SampleModel.groovy
[source,groovy]
[subs="verbatim,attributes"]
----
include::{sample-javafx-groovy}/griffon-app/models/sample/SampleModel.groovy[]
----
<1> Observable property

=== Controller

.sample-javafx-java/griffon-app/controllers/sample/SampleController.java
[source,java]
[subs="verbatim,attributes"]
----
include::{sample-javafx-java}/griffon-app/controllers/sample/SampleController.java[]
----

.sample-javafx-groovy/griffon-app/controllers/sample/SampleController.groovy
[source,groovy]
[subs="verbatim,attributes"]
----
include::{sample-javafx-groovy}/griffon-app/controllers/sample/SampleController.groovy[]
----

=== Service

.sample-javafx-java/griffon-app/services/sample/SampleService.java
[source,java]
[subs="verbatim,attributes"]
----
include::{sample-javafx-java}/griffon-app/services/sample/SampleService.java[]
----

.sample-javafx-groovy/griffon-app/services/sample/SampleService.groovy
[source,groovy]
[subs="verbatim,attributes"]
----
include::{sample-javafx-groovy}/griffon-app/services/sample/SampleService.groovy[]
----

=== View

.sample-javafx-java/griffon-app/views/sample/SampleView.java
[source,java]
[subs="verbatim,attributes"]
----
include::{sample-javafx-java}/griffon-app/views/sample/SampleView.java[]
----
<1> MVC member injected by +link:api/griffon/core/mvc/MVCGroupManager.html[MVCGroupManager]+
<2> Create window and attach it to +link:api/griffon/core/view/WindowManager.html[WindowManager]+
<3> Injected by FXMLLoader
<4> Hook actions by convention

.sample-javafx-java/griffon-app/resources/sample/sample.fxml
[source,xml]
[subs="verbatim,attributes"]
----
include::{sample-javafx-java}/griffon-app/resources/sample//sample.fxml[]
----
<1> Naming convention for automatic action binding

.sample-javafx-groovy/griffon-app/views/sample/SampleView.groovy
[source,groovy]
[subs="verbatim,attributes"]
----
include::{sample-javafx-groovy}/griffon-app/views/sample/SampleView.groovy[]
----
<1> MVC member injected by +link:api/griffon/core/mvc/MVCGroupManager.html[MVCGroupManager]+
<2> Create window and attach it to +link:api/griffon/core/view/WindowManager.html[WindowManager]+
<3> Apply component-to-model binding
<4> Hook actions by convention

=== Resources

.sample-javafx-java/griffon-app/i18n/messages.properties
[source]
----
include::{sample-javafx-java}/griffon-app/i18n/messages.properties[]
----

[conum,data-value=2]_2_