= MessageSource AST Transformation

Any component may gain the ability to resolve messages through a +MessageSource+
instance. You only need annotate the class with +link:api/griffon/transform/MessageSourceAware.html[griffon.transform.MessageSourceAware]+
and it will automatically gain all methods exposed by +link:api/griffon/core/i18n/MessageSource.html[MessageSource]+.

This feature is just a shortcut to avoid reaching for the application instance
from objects that do not hold a reference to it.

Here's an example of a custom bean that's able to resolve messages

[source,groovy]
[subs="verbatim,attributes"]
----
@griffon.transform.MessageSourceAware
class Bean {
    String name
}
----

This class can be used in the following way

[source,groovy]
[subs="verbatim,attributes"]
----
class SampleService {
    @Inject Bean bean

    String lookupValues(String arg) {
        bean.name = arg
        bean.getMessage('some.message.key', [bean.name])
    }
}
----

The application's +MessageSource+ will be injected to annotated beans if no name is
specified as an argument to +MessageSourceAware+. You may define multiple +MessageSource+
bindings as long as you qualify them with a distinct name, such as

[source,java]
[subs="verbatim,attributes"]
----
@ServiceProviderFor(Module.class)
@Named("application")
public class ApplicationModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        bind(MessageSource.class)
            .withClassifier(AnnotationUtils.named("foo"))
            .toProvider(new MessageSourceProvider("foofile"))
            .asSingleton();

        bind(MessageSource.class)
            .withClassifier(AnnotationUtils.named("bar"))
            .toProvider(new MessageSourceProvider("barfile"))
            .asSingleton();
    }
}
----

Then make use of any of these bindings like so

[source,groovy]
[subs="verbatim,attributes"]
----
@griffon.transform.MessageSourceAware('foo')
class Bean {
    String name
}
----