
[[_contributing_issues]]
= Issues

Griffon uses https://github.com/griffon/griffon/issues[Github Issues] to track issues in the
core framework, its documentation and its website. If you've found a bug or wish to see a
particular feature added, this is the place to start. You'll need to create a (free) Github
account in order to either submit an issue or comment on an existing one.

When submitting issues, please provide as much information as possible; and in the
case of bugs, make sure you explain which versions of Griffon and various plugins
you are using. Also, an issue is much more likely to be dealt with if you attach
a reproducible sample application.

== Reviewing issues

There may be a few old issues, some of which may no longer be valid.
The core team can't track down these alone, so a very simple contribution that you
can make is to verify one or two issues occasionally.

Which issues need verification? Just pick an open issue and check whether it's still relevant.

Once you've verified an issue, simply edit it by adding a "Last Reviewed" comment.
If you think the issue can be closed, then also add a "Flagged" comment and a short
explanation why.
