
[[_getting_started_environment_setup]]
= Environment Setup

The following section outlines the minimum environment requirements to get started with Griffon.

== JDK

http://java.oracle.com[JDK7] is the lowest JVM version supported by Griffon. You can safely use
http://java.oracle.com[JDK8] features such as lambdas too. We strongly suggest to use JDK8 if
you're planning to build JavaFX based applications, as JavaFX 8 delivers many enhancements over
JavaFX 2.2 (the version included in JDK7).

== Gradle

http://gradle.org[Gradle] 3.0 was used to thoroughly test the Griffon source code and as such
is guaranteed to work. We suggest installing http://sdkman.io/[SDKMAN] as a means to keep your
Gradle installation up to date. SDKMAN can also be used to install http://github.com/pledbrook/lazybones[Lazybones],
a templating tool for creating Griffon projects.

== Maven

Alternatively you may use Maven instead of Gradle as your build tool of choice. Maven is
a popular choice amongst Java developers; however, it's our firm belief that Gradle delivers
a much better development and user experience. YMMV.

== IDEs

Any IDE that supports Gradle and/or Maven can be used to build a Griffon project.

