
[[_getting_started_environment_setup]]
= Environment Setup

The following section outlines the minimum environment requirements to get started with Griffon.

== JDK

http://java.oracle.com[JDK8] is the lowest JVM version supported by Griffon. We strongly suggest
to use JDK8 update 60 as a minimum if you're planning to build JavaFX based applications.

== Gradle

http://gradle.org[Gradle] 4.0 was used to thoroughly test the Griffon source code and as such
is guaranteed to work. We suggest installing http://sdkman.io/[SDKMAN] as a means to keep your
Gradle installation up to date. SDKMAN can also be used to install http://github.com/pledbrook/lazybones[Lazybones],
a templating tool for creating Griffon projects.

== Maven

Alternatively you may use http://maven.apache.org[Maven] instead of Gradle as your build tool
of choice. Maven is a popular choice amongst Java developers; however, it's our firm belief that
Gradle delivers a much better development and user experience.

== IDEs

Any IDE that supports Gradle and/or Maven can be used to build a Griffon project.

