= Documentation
Andres Almiray
:jbake-type: page
:jbake-status: published
:icons: font

== Griffon in Action

There's a book available from Manning: http://manning.com/almiray[Griffon in Action].
Available in print since June 2012. Source code can be found https://github.com/aalmiray/griffoninaction[here].

The book discusses Griffon 1.x, which is largely compatible with Griffon 2.x in terms
of behavior but some things have changed since, chiefly:

 * There is no longer a `griffon` command. Gradle or Maven are used instead.
 * Plugins are regular JAR files.
 * Groovy is no longer the default language of choice.

== The Griffon Guide

The link:guide/latest/index.html[Griffon Guide] is your first stop for documentation.
It discusses all features available to Griffon applications.

== API Docs

API docs are avilable in link:guide/latest/api/index.html[full Javadoc] and in
link:guide/latest/api-src/index.html[beautified sources].

== All Versions

[cols="4*", options="header"]
|===

| Version
| Guide
| Javadoc
| Source

| {jbake-griffon_version}
| icon:cog[link="guide/{jbake-griffon_version}/index.html"]
| icon:file[link="guide/{jbake-griffon_version}/api/index.html"]
| icon:code[link="guide/{jbake-griffon_version}/api-src/index.html"]

|===
