= Why Griffon
Andres Almiray
:jbake-type:   page
:jbake-status: published
:icons:        font
:linkattrs:

There are multiple options out there when it comes to building desktop applications for the JVM. Why should Griffon be
an option for your next project? Read on to find out.

A icon:star[] denotes a personal favorite.

== icon:magic[] Features! Features! Features!

The Griffon framework provides the following features:

 * Well-defined application lifecycle.
 * MVC components plus lifecycle.
 * Common application structure.
 * Dependency injection via JSR-330.
 * Resource injection.
 * Internationalization support.
 * Lightweight event bus.
 * Centralized error handling.
 * Extensible via plugins.
 * Extremely configurable.

== icon:code[] Programming Language

Griffon is built with Java and runs on the JVM, but that doesn't mean Java is the only language you can use to build
applications with Griffon. The following languages are officially supported by the Griffon {jbake-griffon_version_current}
runtime

 * Java
 * Groovy icon:star[]
 * Kotlin

Additional JVM languages may be supported in the future.

== icon:desktop[] UI Toolkit

Building visual applications would be impossible without an UI toolkit that provides a widget set, user experience and
other bells and whistles. Luckily the JDK delivers not one but two options:

 * Swing
 * JavaFX icon:star[]

Both of them are fully supported by {jbake-griffon_version_current}. But wait, there's more! The aforementioned toolkits
are not the only ones that you can find in the JVM, the following are supported too

 * link:https://pivot.apache.org/[Apache Pivot, window="_blank"]
 * link:https://code.google.com/p/lanterna/[Lanterna, window="_blank"]

Other toolkits may be supported in the future.

== icon:bar-chart[] Memory Footprint

Griffon delivers lots of features and behavior _almost_ for free, as the additional runtime has to be loaded. The good
news is that the deployment size and memory consumption are really low

 * 3K deployment size with Java/Swing or Java/JavaFX.
 * +7M more if Groovy support is added.

== icon:wrench[] Build Tools

Developers care about their toolchain a lot, that is why when confronted with a choice that's does not match their
expectations they may decide to walk away. Fortunately Griffon does not impose too much restrictions when it comes to
the build environment required to build a Griffon project. Projects can be built with any of the following tools

 * link:http://gradle.org/[Gradle, window="_blank"] icon:star[]
 * link:http://maven.apache.org/[Apache Maven, window="_blank"]
 * link:http://ant.apache.org/[Apache Ant, window="_blank"]

These builds tools are well supported by all major Java IDEs. There's no need for special IDE plugins either, just
import the project as you would usually do.
