
[[_controllers]]
= Controllers

Controllers are the entry point for your application's logic. Each controller has
access to their `model` and `view` instances from their respective MVC group.

Controller actions are defined as public methods on a controller class. For example,
in Groovy you'd write

[source,groovy,linenums,options="nowrap"]
----
package sample

import griffon.core.artifact.GriffonController
import griffon.core.controller.ControllerAction
import griffon.annotations.inject.MVCMember
import griffon.annotations.core.Nonnull

@org.kordamp.jipsy.ServiceProviderFor(GriffonController)
class SampleController {
    @MVCMember @Nonnull SampleModel model

    @ControllerAction
    void click() {
        model.clickCount++
    }
}
----

The corresponding code for Java 8 would be

[source,java,linenums,options="nowrap"]
----
package sample;

import griffon.core.artifact.GriffonController;
import griffon.core.controller.ControllerAction;
import griffon.annotations.inject.MVCMember;
import griffon.annotations.core.Nonnull;

@org.kordamp.jipsy.ServiceProviderFor(GriffonController.class)
public class SampleController {
    private SampleModel model;

    @MVCMember
    public void setModel(@Nonnull SampleModel model) {
        this.model = model;
    }

    @ControllerAction
    public void click() {
        runInsideUIAsync(() -> {
            model.setClickCount(model.getClickCount() + 1);
        });
    }
}
----

Actions must follow these rules in order to be considered as such:

 - must have public visibility modifier.
 - name does not match an event handler, i.e, it does not begin with `on`.
 - must pass `{link_is_plain_method}`.
 - must be annotated with `{link_controller_action}` or have `void` as return type.

The application's `{link_action_manager}` will automatically configure an `{link_action}`
instance for each matching controller action. These `Action` instances can be later used
within Views to link them to UI components. The following example shows a Swing View
making use of the configured `clickAction` from `SampleController`:

[source,groovy,linenums,options="nowrap"]
----
package sample

import griffon.core.artifact.GriffonView
import griffon.annotations.inject.MVCMember
import griffon.annotations.core.Nonnull

@org.kordamp.jipsy.ServiceProviderFor(GriffonView)
class SampleView {
    @MVCMember @Nonnull FactoryBuilderSupport builder
    @MVCMember @Nonnull SampleModel model

    void initUI() {
        builder.with {
            application(title: 'Clicker', pack: true)) {
                button(clickAction, label: bind { model.clickCount })
            }
        }
    }
}
----

Controllers can perform other tasks too:

 - listen to <<_events_application_events,application events>>.
 - react to MVC initialization/destruction via a pair of methods (`{link_mvc_group_init}`, `{link_mvc_group_destroy}`).
 - hold references to <<_services,services>>.
 - participate in dependency injection (members must be annotated with `@javax.inject.Inject`).

:leveloffset: 2
include::controllers-actions-and-threads.adoc[]
include::controllers-actionmanager.adoc[]
include::controllers-action-handlers.adoc[]
include::controllers-context.adoc[]
:leveloffset: 1
