
[[_overview_configuration]]
= Configuration

It may seem odd in a framework that embraces "convention-over-configuration"
that we tackle this topic now, but since what configuration there is is typically a
one-off, it is best to get it out the way.

== Basic Configuration

For general configuration, Griffon provides a file called `griffon-app/conf/Config.groovy`.
This file uses Groovy's ConfigSlurper, which is very similar to Java properties files
except it is pure Groovy, hence you can re-use variables and use proper Java types!

Here's a typical configuration file:

[source,groovy,linenums,options="nowrap"]
.griffon-app/conf/sample/swing/groovy/Config.groovy
----
include::{sample-swing-groovy}/griffon-app/conf/sample/swing/groovy/Config.groovy[lines=18..-1]
----

You can define this file using Java too:

[source,java,linenums,options="nowrap"]
.griffon-app/conf/sample/swing/java/Config.java
----
include::{sample-swing-java}/griffon-app/conf/sample/swing/java/Config.java[lines=18..-1]
----

Or if you prefer properties files, then do the following:

[source,java,linenums,options="nowrap"]
.griffon-app/resources/Config.properties
----
application.title = Swing + Groovy
application.startupGroups = sample
application.autoShutdown = true
mvcGroups.sample.model = sample.swing.groovy.SampleModel
mvcGroups.sample.view = sample.swing.groovy.SampleView
mvcGroups.sample.controller = sample.swing.groovy.SampleController
----

Finally, you can also use XML

[source,xml,linenums,options="nowrap"]
.griffon-app/resources/Config.xml
----
<?xml version="1.0"?>
<configuration>
    <application>
        <title>Swing + Groovy</title>
        <startupGroups>sample</startupGroups>
        <autoShutdown>true</autoShutdown>
    </application>
    <mvcGroups>
        <sample>
            <model>sample.swing.groovy.SampleModel</model>
            <view>sample.swing.groovy.SampleView</view>
            <controller>sample.swing.groovy.SampleController</controller>
        </sample>
    </mvcGroups>
</configuration>
----

Take special note that these last two files must be placed under `griffon-app/resources` instead.

The application's runtime configuration is available through the `configuration` property
of the application instance. This configuration instance is *read-only*; you can't modify
its contents in any way.

There are 3 configuration keys that control the application's behavior:

[horizontal]
application.title:: Defines the default title for the application.
application.startupGroups:: Defines a list of MVC groups to be initialized during the <<_overview_lifecycle_startup,Startup>>
phase. Refer to the <<_mvc,MVC chapter>> to know more about MVC groups.
application.autoShutdown:: Controls if the application should shutdown when no windows are visible. Set to `true`by
default.

Additional configuration keys may be added as you deem fit. Take note that the `mvcGroups` prefix has special meaning.
Refer to the <<_mvc,MVC chapter>> to know more about the different options available to you.

== Internationalization Support

Configuration files are i18n aware, which means you can append
locale specific strings to a configuration file; for example, `Config_de_CH.groovy`.
Locale suffixes are resolved from least to most specific; for a locale with
`language = 'de'`, `country = 'CH'` and `variant = 'Basel'`, the following files are loaded in order:

 * `Config.groovy`
 * `Config.properties`
 * `Config_de.groovy`
 * `Config_de.properties`
 * `Config_de_CH.groovy`
 * `Config_de_CH.properties`
 * `Config_de_CH_Basel.groovy`
 * `Config_de_CH_Basel.properties`

The current `java.util.Locale` is used to determine values for language, country and variant.

== Mutable Configuration

As mentioned before, the default application configuration is made *read-only*, however there's a way to make it
mutable; you simply must wrap the `{link_configuration}` instance with a `{link_mutable_configuration}`. You can accomplish
this by registering an appropriate implementation of `{link_configuration_decorator_factory}`, for example
`{link_mutable_configuration_decorator_factory}`. You'll have to register this class with a module:

[source,java,linenums,options="nowrap"]
.com.acme.ApplicationModule.java
----
package com.acme

import griffon.core.injection.Module;
import org.codehaus.griffon.runtime.core.injection.AbstractModule;
import org.kordamp.jipsy.ServiceProviderFor;
import org.codehaus.griffon.runtime.core.configuration.ConfigurationDecoratorFactory;
import org.codehaus.griffon.runtime.core.configuration.MutableConfigurationDecoratorFactory;

import static griffon.util.AnnotationUtils.named;

@ServiceProviderFor(Module.class)
public class ApplicationModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        bind(ConfigurationDecoratorFactory.class)
            .to(MutableConfigurationDecoratorFactory.class)
            .asSingleton();
    }
}
----

== Conditional Blocks

There are times where a configuration value may dependent on an enviromental setting such as the current
<<_overview_metadata_environment,Application Environment>>. All types of configuration files (properties, Groovy scripts,
class based resource bundles) support the notion of conditional blocks. Take for example the following datasource configuration
in Groovy script format:

[source, groovy]
.griffon-app/resources/DataSource.groovy
----
dataSource.driverClassName = 'org.h2.Driver'
environments {
    development {
        dataSource.url = 'jdbc:h2:mem:${application_name}-dev'
    }
    test {
        dataSource.url = 'jdbc:h2:mem:${application_name}-test'
    }
    production {
        dataSource.url = 'jdbc:h2:file:/opt/${application_name}/data/db'
    }
}
----

The same configuration in properties format:

[source, java]
.griffon-app/resources/DataSource.properties
----
dataSource.driverClassName = org.h2.Driver
environments.development.dataSource.url = jdbc:h2:mem:${application_name}-dev
environments.test.dataSource.url = jdbc:h2:mem:${application_name}-test
environments.production.dataSource.url = jdbc:h2:file:/opt/${application_name}/data/db
----

Or in XML format:

[source, xml]
.griffon-app/resources/DataSource.xml
----
<?xml version="1.0"?>
<configuration>
    <dataSource>
        <driverClassName>org.h2.Driver</driverClassName>
    </dataSource>
    <environments>
        <development>
            <dataSource>
                <url>jdbc:h2:mem:${application_name}-dev</url>
            </dataSource>
        </development>
        <test>
            <dataSource>
                <url>jdbc:h2:mem:${application_name}-test</url>
            </dataSource>
        </test>
        <production>
            <dataSource>
                <url>jdbc:h2:mem:${application_name}-prod</url>
            </dataSource>
        </production>
    </environments>
</configuration>
----

Or as a class based `ResourceBundle` subclass:

[source, java]
.griffon-app/conf/DataSource.java
----
import java.util.Map;

import griffon.util.AbstractMapResourceBundle;

import static griffon.util.CollectionUtils.map;

public class DataSource extends AbstractMapResourceBundle {
    @Override
    protected void initialize(Map<String, Object> entries) {
        map(entries)
            .e("dataSource", map()
                .e("driverClassName", "org.h2.Driver")
            )
            .e("environments", map()
                .e("development", map()
                    .e("dataSource", map()
                        .e("url", "jdbc:h2:mem:sample-dev")
                    )
                )
                .e("test", map()
                    .e("dataSource", map()
                        .e("url", "jdbc:h2:mem:sample-test")
                    )
                )
                .e("production", map()
                    .e("dataSource", map()
                        .e("url", "jdbc:h2:file:/opt/sample/data/db")
                    )
                )
            );
    }
}
----

The conditional block in this case is `environments`; the value of `{link_environment}` will dictate the actual value
associated with the `dataSource.url` key. There are 3 conditional blocks defined by default:

|====
| Name         | Default value
| environments | Environment.getName()
| projects     | Metadata.getApplicationName()
| platforms    | GriffonApplicationUtils.getPlatform()
|====

You may define additional conditional blocks as needed, but you must do it by defining appropriate binding overrides
for the following types in a custom <<_overview_modules,Module>> of your choice:

 * `griffon.util.PropertiesReader` for properties files.
 * `griffon.util.ResourceBundleReader` for class based `ResourceBundle` and XML.
 * `griffon.util.ConfigReader` for Groovy scripts.

== Configuration Injection

Configuration values may be injected into beans if the {link_configured} annotation is applied to a field or setter method
of a type that's bound to the application's dependency container. Take for example the following configuration

[source,groovy,linenums,options="nowrap"]
.griffon-app/conf/sample/swing/groovy/Config.groovy
----
application {
    title = 'JavaFX + Groovy'
    startupGroups = ['sample']
    autoShutdown = true
}
props {
    string = 'string'
    number = 42
    date   = '1970-12-24'
}
mvcGroups {
    'sample' {
        model      = 'sample.javafx.groovy.SampleModel'
        view       = 'sample.javafx.groovy.SampleView'
        controller = 'sample.javafx.groovy.SampleController'
    }
}
----

Any of those configuration values may be set on a managed bean, such as the `SampleModel` class

[source,groovy,linenums,options="nowrap"]
.griffon-app/models/sample/javafx/groovy/SampleModel.groovy
----
package sample.javafx.groovy

import griffon.core.artifact.GriffonModel
import griffon.metadata.ArtifactProviderFor
import griffon.transform.FXObservable
import griffon.core.configuration.Configured

@ArtifactProviderFor(GriffonModel)
class SampleModel {
    @FXObservable String input
    @FXObservable String output

    @Configured('application.title')
    String title

    @Configured('props.string')
    String string

    @Configured('props.number')
    int number

    @Configured(value = 'props.date', format = 'YYYY-MM-dd')
    Date date

    @Configured(value = 'props.undefined', defaultValue = 'undefined')
    String undefined
}
----

Values will be injected before `@PostConstruct` is triggered on the managed bean. Type conversion will be carried out
using <<_resources_property_editors,property editors>>.

