
[[_overview_modules]]
= Modules

``{link_module}``s define components that can be injected using the JSR-330 API.
Module definitions are highly influenced by the Guice 3.x API; however, they do not
impose a strict dependency on Guice.

[[_overview_module_definition]]
== Module Definition

All modules must implement the `{link_module}` interface shown next:

[source,java,linenums,options="nowrap"]
----
include::{rootprojectdir}/subprojects/griffon-core/src/main/java/griffon/core/injection/Module.java[lines=27..-1]
----

They also require a well defined name. This can be achieved by annotating the module
class with `@javax.inject.Named`. If a value for `@javax.inject.Named` is not defined, then
one will be automatically calculated using the fully qualified class name. For example:

[source,java,linenums,options="nowrap"]
----
package org.example;

import griffon.core.injection.Module;
import org.codehaus.griffon.runtime.core.injection.AbstractModule;
import org.kordamp.jipsy.annotations.ServiceProviderFor;

import javax.inject.Named;

@ServiceProviderFor(Module.class)
@Named
public class CustomModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        // bindings
    }
}
----

Results in a module named `org.example.custom`; whereas the following definition

[source,java,linenums,options="nowrap"]
----
package org.example;

import griffon.core.injection.Module;
import org.codehaus.griffon.runtime.core.injection.AbstractModule;
import org.kordamp.jipsy.annotations.ServiceProviderFor;

import javax.inject.Named;

@ServiceProviderFor(Module.class)
@Named("custom")
public class CustomModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        // bindings
    }
}
----

Results in a module simply called `custom`. A module may depend on another module; when
that's the case, then the bindings of this module are processed after their dependencies. This
allows dependent modules to override bindings made by their dependencies. Module dependencies
are specified using the `{link_depends_on}` annotation, like so:

[source,java,linenums,options="nowrap"]
----
import griffon.core.injection.Module;
import griffon.annotations.inject.DependsOn;
import org.codehaus.griffon.runtime.core.injection.AbstractModule;
import org.kordamp.jipsy.annotations.ServiceProviderFor;

import javax.inject.Named;

@ServiceProviderFor(Module.class)
@DependsOn("parent-module")
@Named
public class CustomModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        // bindings
    }
}
----

[[_overview_module_configuration]]
== Module Configuration

Modules perform their duty by defining bindings, of which there are 4 kinds:

 * {link_instance_binding}
 * {link_target_binding}
 * {link_provider_binding}
 * {link_provider_type_binding}

Bindings have a scope of either `singleton` or `prototype`. `InstanceBinding` is the only
binding that has `singleton` as implicit scope; this setting can't be changed.
All bindings accept a `classifier` or an `classifier_type`. Classifiers are annotations that
have been annotated with `@javax.inject.Qualifier`. You must specify one or the other but
not both; `classifier` has precedence over `classifier_type`.

[[_overview_instance_binding]]
=== Instance Binding

This binding is used to define explicit and eager singletons, for example:

[source,java,options="nowrap"]
----
bind(Calculator.class)
    .toInstance(new GroovyShellCalculator());
----

Consumers of this binding will typically define the following:

[source,java,options="nowrap"]
----
@Inject private Calculator calculator;
----

Notice that the field type matches the _source_ type defined in the binding.

[[_overview_target_binding]]
=== Target Binding

This binding enables you to specify the _source_ type and _target_ type. Typically the
_source_ is an interface while the _target_ is a concrete implementation. If the _target_
is omitted, then the binding assumes the _source_ to be a concrete type.

[source,java,options="nowrap"]
----
bind(Calculator.class)
    .to(GroovyShellCalculator.class);
----

Consumers of this binding will use the following form:

[source,java,options="nowrap"]
----
@Inject private Calculator calculator;
----

On the other hand, if the binding where to be defined as

[source,java,options="nowrap"]
----
bind(GroovyShellCalculator.class);
----

then the consumers must use the same matching _source_/_target_ type, that is

[source,java,options="nowrap"]
----
@Inject private GroovyShellCalculator calculator;
----

Attempting to use the base type `Calculator` by the consumer will result in an unresolved binding.

[[_overview_provider_binding]]
=== Provider Binding

This binding behaves like a factory, giving you the power to decide with extreme precision
how the instance should be created. Bindings of this type require an eager instance of
type `javax.inject.Provider`.

[source,java,options="nowrap"]
----
bind(Calculator.class)
    .toProvider(new CalculatorProvider());
----

Consumers of this binding will use the following form:

[source,java,options="nowrap"]
----
@Inject private Calculator calculator;
----

[[_overview_provider_type_binding]]
=== Provider Type Binding

Finally we have the most flexible binding as it lets you specify a `javax.injectProvider`
type that will be used to lazily instantiate the provider before obtaining the type instance.

[source,java,options="nowrap"]
----
bind(Calculator.class)
    .toProvider(CalculatorProvider.class);
----

Consumers of this binding will use the following form:

[source,java,options="nowrap"]
----
@Inject private Calculator calculator;
----

[[_overview_constant_value_binding]]
=== Constant Value Binding

You may use a variation of <<_overview_instance_binding, Instance Binding>> to bind a constant value, for example an instance
of `java.lang.String`. You *must* make sure to always use a qualifier. For example, the following constant value

[source,java,options="nowrap"]
----
bind(String.class)
    .withClassifier(named(GithubAPI.GITHUB_API_URL_KEY))
    .toInstance("https://api.github.com");
----

Can be injected into a target instance as

[source,java,options="nowrap"]
----
public class GithubBean {
    @Inject @Named(GithubAPI.GITHUB_API_URL_KEY)
    private String githubApiUrl;
}
----

[[_overview_bindings_additional_settings]]
== Additional Settings

All bindings (with one particular exception) accept the following additional settings:

.withClassifierType

This method is used to define an additional annotation type that's been marked as a `@Qualifier` (such as `@javax.inject.Named`)
that should go along with the declared binding. Any qualifiers found in the _target_ type (or `Provider`) will be overridden
by this setting.

.withClassifier

Similar to the previous setting, this one allows you to supply an annotation instance, enabling the setting of a custom
annotation property, such as the `value` of `@javax.inject.Named`. Here's an excerpt of the default bindings provided
by the Griffon runtime:

[source,java,options="nowrap"]
----
bind(Context.class)
    .withClassifier(griffon.util.AnnotationUtils.named("applicationContext"))
    .toProvider(DefaultContextProvider.class)
    .asSingleton();
----

Any qualifiers found in the _target_ (or `Provider`) will be overridden by this setting.

.asSingleton

If omitted, the binding will be placed in `prototype` scope. The only binding that does not conform to this rule is *InstanceBinding*,
as it will be automatically placed in `singleton` scope.

[[_overview_binding_equivalencies]]
== Binding Equivalencies

Any binding can be overridden by an equivalent binding. The following table describes the equivalencies between bindings:

[cols="a,a",options="header"]
|===

| Binding
| Equivalence

|
[source,java,options="nowrap"]
----
bind(Calculator.class)
    .to(GroovyShellCalculator.class);
----
|
[source,java,options="nowrap"]
----
bind(Calculator.class)
    .toProvider(GroovyShellCalculatorProvider.class);
----

|
[source,java,options="nowrap"]
----
bind(Calculator.class)
    .to(GroovyShellCalculator.class);
----
|
[source,java,options="nowrap"]
----
bind(Calculator.class)
    .toProvider(new GroovyShellCalculatorProvider());
----

|
[source,java,options="nowrap"]
----
bind(Calculator.class)
    .toProvider(GroovyShellCalculatorProvider.class);
----
|
[source,java,options="nowrap"]
----
bind(Calculator.class)
    .toProvider(new GroovyShellCalculatorProvider());
----

|===

NOTE: Equivalent bindings must match qualifiers too.


[[_overview_module_evictions]]
== Module Evictions

Given binding equivalences a module may override bindings supplied by other modules, but you can't avoid the original
bindings from being added in the first case. With module evictions is possible for a module to evict another one,
effectively barring the evicted module from contributing its bindings. Let's say there's a module named "foo" defined
as follows

[source, java]
----
import griffon.core.injection.Module;
import griffon.annotations.inject.DependsOn;
import org.codehaus.griffon.runtime.core.injection.AbstractModule;
import org.kordamp.jipsy.annotations.ServiceProviderFor;

import javax.inject.Named;

@Named("foo")
@ServiceProviderFor(Module.class)
public class FooModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        // binding definitions
    }
}
----

You may evict this module by defining another module annotated with `{link_evicts}`, such as

[source, java]
----
import griffon.core.injection.Module;
import griffon.annotations.inject.DependsOn;
import griffon.annotations.inject.Evicts;
import org.codehaus.griffon.runtime.core.injection.AbstractModule;
import org.kordamp.jipsy.annotations.ServiceProviderFor;

import javax.inject.Named;

@Named("foo")
@Evicts("foo")
@ServiceProviderFor(Module.class)
public class FooEvictorModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        // binding definitions
    }
}
----

The evicting module (`FooEvictorModule`)  has to have the same name as the evicted module (`FooModule`) hence why both
modules are annotated with `@Named("foo")`.

[[_overview_guice_injector]]
== The Guice Injector

The dependency `griffon-guice-{griffon-version}` uses {link_google_guice} to implement the JSR-330 API
that `griffon-core-{griffon-version}` requires. As an additional feature, this dependency can automatically
load Guice modules during startup. The only requirement is a metadata file that defines the module class
that should be loaded.

Here's an example that reuses the Quartz Scheduler from {link_apache_onami}.

[source,java,linenums,options="nowrap"]
----
package com.acme;

import org.apache.onami.scheduler.QuartzModule;
import com.google.inject.Module;
import org.kordamp.jipsy.annotations.ServiceProviderFor;

@ServiceProviderFor(Module.class)
public class MyQuartzModule extends QuartzModule {
    @Override
    protected void schedule() {
        scheduleJob(MyJobClass.class);
    }
}
----

When compiled, this class generates a metadata file at `META-INF/services/com.google.inject.Module` with
contents similar to

[source,java,linenums,options="nowrap"]
----
# Generated by org.kordamp.jipsy.processor.service.ServiceProviderProcessor (0.4.0)
# Thu, 7 Aug 2014 21:02:58 +0200
com.acme.MyQuartzModule
----

Of course the usage of `@ServiceProviderFor` is just a convenience; you can generate the metadata file
by other means. The important thing is that the file must be available in the classpath.

Guice modules are added after all Griffon modules; this means they have the chance to override any bindings
set by the Griffon modules.

