= Griffon 2.0.0.BETA2 Released
Andres Almiray
2014-06-20
:jbake-type: post
:jbake-status: published
:category: news
:idprefix:

== Griffon 2.0.0.BETA2 Released

The Griffon team is happy to announce the release of Griffon 2.0.0.BETA2!

This release continues the work of the first beta release by strengthening the build
options available to Griffon application developers.

The following list summarizes the changes brought by this release:

 * The specialized JavaFXGriffonView failed to locate a suitable FXML file by convention.
   This is now fixed.
 * Lazybones templates produce a `pom.xml` besides `build.gradle`. You can now build
   Griffon projects with either Maven or Gradle.
 * a Gradle plugin that applies the Griffon project conventions is also available.
   The Lazybones templates are aware of this plugin.
 * more content added to the http://griffon.github.io/griffon/guide/[Griffon Guide].
 * API javadoc available online at http://griffon.github.io/griffon/guide/api/
 * beautified API sources available online at http://griffon.github.io/griffon/guide/api-src/

We look forward to your feedback. Please report any problems you find to the Griffon User list,
or better yet, file a bug at http://jira.codehaus.org/browse/griffon

Remember you can also contact the team on Twitter: http://twitter.com/theaviary[@theaviary].

Many thanks to all who contributed to this release!

-- The Griffon Team
