= Griffon 2.7.0 Released
Andres Almiray
2016-06-20
:jbake-type: post
:jbake-status: published
:category: news
:linkattrs:
:idprefix:
:path-griffon-core: /guide/2.7.0/api/griffon/core

== Griffon 2.7.0 Released

The Griffon team is happy to announce the release of Griffon 2.7.0!

The following list summarizes the changes brought by this release:

* [Build] Griffon Gradle plugin works with Gradle 2.12 and newer.
* [Runtime] `metaComponent` builder factory works as expected.
* [Templates] New project template: `griffon-javafx-kotlin`.

A more detailed description of the changes and compatibility issues can be found at the link:/releasenotes/griffon_2.7.0.html[release notes, window="_blank"].

We look forward to your feedback. Please report any problems you find to the Griffon User list,
or better yet, file a bug at https://github.com/griffon/griffon/issues

Remember you can also contact the team on Twitter: https://twitter.com/theaviary[@theaviary].

Many thanks to all who contributed to this release!

The Griffon Team
