= Griffon 2.0.0.RC2 Released
Andres Almiray
2014-08-11
:jbake-type: post
:jbake-status: published
:category: news
:idprefix:

== Griffon 2.0.0.RC2 Released

The Griffon team is happy to announce the release of Griffon 2.0.0.RC2!

This is the first release candidate of Griffon 2.0.0. If all goes according to plan the next release
will be 2.0.0 final in a few weeks time.

The following list summarizes the changes brought by this release:

 * Groovy support upgraded to Groovy 2.3.6.
 * Pivot support upgraded to Groovy 2.0.4.
 * Lots of updates applied to Lazybones application templates.
 * Properly sort auto-loaded modules in tests (test modules are placed last).
 * More content added to the link:../guide/2.0.0.RC2/index.html[Griffon Guide].

We look forward to your feedback. Please report any problems you find to the Griffon User list,
or better yet, file a bug at http://github.com/griffon/griffon/issues

Remember you can also contact the team on Twitter: http://twitter.com/theaviary[@theaviary].

Many thanks to all who contributed to this release!

The Griffon Team
