= Griffon 2.0.0.RC1 Released
Andres Almiray
2014-07-29
:jbake-type: post
:jbake-status: published
:category: news
:idprefix:

== Griffon 2.0.0.RC1 Released

The Griffon team is happy to announce the release of Griffon 2.0.0.RC1!

This is the first release candidate of Griffon 2.0.0. If all goes according to plan the next release
will be 2.0.0 final in a few weeks time.

The following list summarizes the changes brought by this release:

 * Groovy support upgraded to Groovy 2.3.5.
 * Several build plugins updated to their latest versions.
 * Addition of a master pom file for application projects.
 * Enable +mavenLocal()+ on gradle-griffon plugins by default.
 * Lots of updates applied to Lazybones application templates.
 * More content added to the link:../guide/2.0.0.RC1/index.html[Griffon Guide].

We look forward to your feedback. Please report any problems you find to the Griffon User list,
or better yet, file a bug at link:https://github.com/griffon/griffon/issues[]

Remember you can also contact the team on Twitter: https://twitter.com/theaviary[@theaviary].

Many thanks to all who contributed to this release!

The Griffon Team
