= Griffon 2.10.0 Released
Andres Almiray
2017-03-02
:jbake-type: post
:jbake-status: published
:category: news
:linkattrs:
:idprefix:
:path-griffon-core: /guide/2.10.0/api/griffon/core

== Griffon 2.10.0 Released

The Griffon team is happy to announce the release of Griffon 2.10.0!

The following list summarizes the changes brought by this release:

 * Modules can be evicted during bootstrap, effectively skipping their bindings from being contributed to the injector.
 * New `ResourceBundleReader` class delivers conditional block support to `java.util.ResourceBundle`, similar to what `ConfigReader` does for Groovy scripts.
 * New `PropertiesReader` class delivers conditional block support to `java.util.Properties`, similar to what `ConfigReader` does for Groovy scripts.
 * JavaFX Support
 ** JavaFX bindings, properties, and collections added in 2.9.1 have been relocated to other packages.
 ** New `ElementObservableList` class triggers updates when an element is updated.
 ** New resetable properties support.
 ** Configurable strategy for matching actions defined in FXML: `griffon.javafx.support.ActionMatcher`.
 * New properties for the `org.codehaus.griffon.griffon` Gradle plugin that give you more control on non-application projects.

A more detailed description of the changes and compatibility issues can be found at the link:/releasenotes/griffon_2.10.0.html[release notes, window="_blank"].

We look forward to your feedback. Please report any problems you find to the Griffon User list,
or better yet, file a bug at http://github.com/griffon/griffon/issues

Remember you can also contact the team on Twitter: http://twitter.com/theaviary[@theaviary].

Many thanks to all who contributed to this release!

The Griffon Team

