= Griffon 2.13.0 Released
Andres Almiray
2017-12-01
:jbake-type: post
:jbake-status: published
:category: news
:linkattrs:
:idprefix:
:path-griffon-core: /guide/2.13.0/api/griffon/core

== Griffon 2.13.0 Released

The Griffon team is happy to announce the release of Griffon 2.13.0!

The following list summarizes the changes brought by this release:

 * Custom PropertyEditor support for @Configured and @MVCMember.
 * @Contextual injection support for non-griffon artifacts.
 * Allow FXMLLoader to be configured by View subclasses
 * New `ObservableStream` class provides stream operations on top of an observable collection.

A more detailed description of the changes and compatibility issues can be found at the link:/releasenotes/griffon_2.13.0.html[release notes, window="_blank"].

We look forward to your feedback. Please report any problems you find to the Griffon User list,
or better yet, file a bug at http://github.com/griffon/griffon/issues

Remember you can also contact the team on Twitter: http://twitter.com/theaviary[@theaviary].

Many thanks to all who contributed to this release!

The Griffon Team

