= Griffon 2.9.0 Released
Andres Almiray
2016-12-01
:jbake-type: post
:jbake-status: published
:category: news
:linkattrs:
:idprefix:
:path-griffon-core: /guide/2.7.0/api/griffon/core

== Griffon 2.9.0 Released

The Griffon team is happy to announce the release of Griffon 2.9.0!

The following list summarizes the changes brought by this release:

 * `JavaFXAction` has the following updates:
 ** `style`: used to set style on the bound widget.
 ** `graphic`: used to set the graphic node on the bound widget.
 ** `graphicStyle`: used to set style on the graphic node of the bound widget.
 ** `graphicStyleClass`: used to set style classes on the graphic node of the bound widget.
 * Added an UI Thread proxy `ObservableSet`; all of its updates will be triggered inside the UI thread.
 * Added an UI Thread proxy `ObservableMap`; all of its updates will be triggered inside the UI thread.
 * New `BindingUtils` class provides lots of useful binding and property factories:
 ** Join `ObservableList`/`ObservableSet`/`ObservableMap` to `StringBinding`.
 ** Reduce `ObservableList`/`ObservableSet`/`ObservableMap` to `ObjectBinding`.
 ** Reduce `ObservableList`/`ObservableSet`/`ObservableMap` then map to X; where X may be a wrapper type, String or a type `R`.
 ** Map elements of `ObservableList`/`ObservableSet`/`ObservableMap` to X then reduce; where X may be a wrapper type, String or a type `R`.
 ** convert `ObservableValue<X>` to is corresponding `XBinding`.
 ** convert `ObservableXValue` to `ObjectBinding<X>`.
 ** Create bindings that update their value and notify listeners inside the UI thread.

A more detailed description of the changes and compatibility issues can be found at the link:/releasenotes/griffon_2.9.0.html[release notes, window="_blank"].

We look forward to your feedback. Please report any problems you find to the Griffon User list,
or better yet, file a bug at http://github.com/griffon/griffon/issues

Remember you can also contact the team on Twitter: http://twitter.com/theaviary[@theaviary].

Many thanks to all who contributed to this release!

The Griffon Team
