= Griffon 2.11.0 Released
Andres Almiray
2017-06-01
:jbake-type: post
:jbake-status: published
:category: news
:linkattrs:
:idprefix:
:path-griffon-core: /guide/2.11.0/api/griffon/core

== Griffon 2.11.0 Released

The Griffon team is happy to announce the release of Griffon 2.11.0!

The following list summarizes the changes brought by this release:

 * Configuration can be written in XML format.
 * Configuration values may be injected via `@Configured`.
 * Typed MVC groups are now supported.
 * `ThreadingHandler` can now execute code on a new thread regardless of the invoking thread.
 * Action Support
 ** Action metadata can be used to support ``ActionHandler``s.
 ** Controller actions may return a value.
 ** Controller actions may be identified by `@ControllerAction`.
 * New `MatchingBindings` class provides matching capabilities on `ObservableList`/`ObservableSet`/`ObservableMap`
 ** Apply `allMatch`, `anyMatch`, and `noneMatch` predicates.
 * JavaFX Support
 ** New widget `IndexedCardPane`.
 ** New widget `NamedCardPane`.
 ** New `TableViewFormat` and `TableViewModel` classes. Create tables effortlessly.

A more detailed description of the changes and compatibility issues can be found at the link:/releasenotes/griffon_2.11.0.html[release notes, window="_blank"].

We look forward to your feedback. Please report any problems you find to the Griffon User list,
or better yet, file a bug at https://github.com/griffon/griffon/issues

Remember you can also contact the team on Twitter: https://twitter.com/theaviary[@theaviary].

Many thanks to all who contributed to this release!

The Griffon Team

