= Griffon 2.5.0 Released
Andres Almiray
2015-12-01
:jbake-type: post
:jbake-status: published
:category: news
:linkattrs:
:idprefix:
:path-griffon-core: /guide/2.5.0/api/griffon/core

== Griffon 2.5.0 Released

The Griffon team is happy to announce the release of Griffon 2.5.0!

The following list summarizes the changes brought by this release:

 * Upgraded to Groovy 2.4.5
 * A new interface, `ObservableContext`, allows publication of events when a property is added, removed, or updated.
 * `Context` now sports typed getters.
 * `Context` can inject any members annotated with `@Contextual` at any given time.
 * Contextual injections on MVC members are automatically cleanup up during the destroy lifecycle phase of each MVC member.
 * `JavaFXAction` has the following updates:
 ** a `visible` property that controls the visibility of the bound widget.
 ** a `styleClass` property that controls the stylable classes of the bound widget.

A more detailed description of the changes and compatibility issues can be found at the link:/releasenotes/griffon_2.5.0.html[release notes, window="_blank"].

We look forward to your feedback. Please report any problems you find to the Griffon User list,
or better yet, file a bug at http://github.com/griffon/griffon/issues

Remember you can also contact the team on Twitter: http://twitter.com/theaviary[@theaviary].

Many thanks to all who contributed to this release!

The Griffon Team
