= Griffon 2.4.0 Released
Andres Almiray
2015-09-01
:jbake-type: post
:jbake-status: published
:category: news
:linkattrs:
:idprefix:
:path-griffon-core: /guide/2.4.0/api/griffon/core

== Griffon 2.4.0 Released

The Griffon team is happy to announce the release of Griffon 2.4.0!

The following list summarizes the changes brought by this release:

 * Upgraded to Groovy 2.4.4 and Guice 4.0.
 * New GDSL for SwingBuilder nodes.
 * Guice modules may be annotated with `griffon.inject.DependsOn`.
 * Query for a key's existence on a specific `griffon.core.Context` or its hierarchy.
 * Updates to MVCGroup relationship behavior.
 * Java8 specific property editors added:
 ** `java.time.LocalDate`, `java.time.LocalDateTime`, `java.time.LocalTime`.
 ** extensions for `java.util.Calendar` and `java.util.Date` that can handle `java.time` types.
 * JavaFX support received lots up updates:
 ** new AST transformations: `@ListChangeListener` and `@MapChangeListener`.
 ** Automatically wrap listeners generated by `@ChangeListener`, `@InvalidationListener`, `@ListChangeListener` and `@MapChangeListener` with their Weak reference counterparts.
 ** `JavaFXUtils` can bind `ToolBar` buttons to actions.
 ** `JavaFXUtils.findElement` works with more containers.
 ** `GraphicPropertyEditor` can handle plain resources.
 ** New property editors:
 *** `LinearGradientPropertyEditor`, `RadialGradientPropertyEditor` and `PaintPropertyEditor`.

A more detailed description of the changes and compatibility issues can be found at the link:/releasenotes/griffon_2.4.0.html[release notes, window="_blank"].

We look forward to your feedback. Please report any problems you find to the Griffon User list,
or better yet, file a bug at http://github.com/griffon/griffon/issues

Remember you can also contact the team on Twitter: http://twitter.com/theaviary[@theaviary].

Many thanks to all who contributed to this release!

The Griffon Team
