= Griffon 2.11.0 Released
Andres Almiray
2017-09-01
:jbake-type: post
:jbake-status: published
:category: news
:linkattrs:
:idprefix:
:path-griffon-core: /guide/2.12.0/api/griffon/core

== Griffon 2.12.0 Released

The Griffon team is happy to announce the release of Griffon 2.12.0!

The following list summarizes the changes brought by this release:

 * Pivot support upgraded to 2.0.5.
 * JavaFX Gradle project templates switched to ink:https://github.com/FibreFoX/javafx-gradle-plugin[FibreFoX/javafx-gradle-plugin]
in order to have feature parity with their Maven counterparts.
 * Project templates now include `mvnw` wrapper.
 * Use ${token} instead of @token@ in resource files.
 * New MetaComponent support for JavaFX Views using FXML.

A more detailed description of the changes and compatibility issues can be found at the link:/releasenotes/griffon_2.12.0.html[release notes, window="_blank"].

We look forward to your feedback. Please report any problems you find to the Griffon User list,
or better yet, file a bug at http://github.com/griffon/griffon/issues

Remember you can also contact the team on Twitter: http://twitter.com/theaviary[@theaviary].

Many thanks to all who contributed to this release!

The Griffon Team

