= Griffon 2.0.0.BETA3 Released
Andres Almiray
2014-07-03
:jbake-type: post
:jbake-status: published
:category: news
:idprefix:

== Griffon 2.0.0.BETA3 Released

The Griffon team is happy to announce the release of Griffon 2.0.0.BETA3!

This release marks Griffon 2.0 as feature complete. Remaining efforts will be concentrated
in getting the Guide up to date and getting base plugins out of the door
(miglayout, glazedlists, datasource, etc).

The following list summarizes the changes brought by this release:

 * Build has been upgraded to Gradle 2.0. This is the new baseline.
 * Lazybones templates allow creation of artifacts (leveraging Lazybones new subtemplate feature).
 * Spock is added as default testCompile dependency on project templates (those configured with Gradle).
 * There's a second gradle plugin (`gradle-griffon-build-plugin`) used in plugin projects.
 * more content added to the https://griffon.github.io/griffon/guide/[Griffon Guide].

We look forward to your feedback. Please report any problems you find to the Griffon User list,
or better yet, file a bug at link:https://github.com/griffon/griffon/issues[]

Remember you can also contact the team on Twitter: https://twitter.com/theaviary[@theaviary].

Many thanks to all who contributed to this release!

The Griffon Team
